// Complete list of ALL NSE listed stocks
// This file contains stocks not covered by NSE index APIs
// Used as fallback when live data is not available

export const ALL_NSE_STOCKS = [
    // SME & Small Cap Stocks
    { symbol: 'YESBANK.NS', name: 'Yes Bank', sector: 'Banking' },
    { symbol: 'VODAFONE.NS', name: 'Vodafone Idea', sector: 'Telecom' },
    { symbol: 'SUZLON.NS', name: 'Suzlon Energy', sector: 'Power' },
    { symbol: 'IDEA.NS', name: 'Vodafone Idea', sector: 'Telecom' },
    { symbol: 'PNB.NS', name: 'Punjab National Bank', sector: 'Banking' },
    { symbol: 'RBLBANK.NS', name: 'RBL Bank', sector: 'Banking' },
    { symbol: 'IRFC.NS', name: 'Indian Railway Finance', sector: 'Finance' },
    { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam', sector: 'Infrastructure' },
    { symbol: 'RAILTEL.NS', name: 'RailTel Corporation', sector: 'IT' },
    { symbol: 'IRCON.NS', name: 'Ircon International', sector: 'Infrastructure' },
    { symbol: 'IRCTC.NS', name: 'IRCTC', sector: 'Railways' },
    { symbol: 'RITES.NS', name: 'RITES', sector: 'Engineering' },
    { symbol: 'HUDCO.NS', name: 'HUDCO', sector: 'Finance' },
    { symbol: 'NBCC.NS', name: 'NBCC India', sector: 'Infrastructure' },
    { symbol: 'NCC.NS', name: 'NCC Limited', sector: 'Infrastructure' },
    { symbol: 'NHPC.NS', name: 'NHPC', sector: 'Power' },
    { symbol: 'NMDC.NS', name: 'NMDC', sector: 'Mining' },
    { symbol: 'NLCINDIA.NS', name: 'NLC India', sector: 'Power' },
    { symbol: 'NFL.NS', name: 'National Fertilizers', sector: 'Fertilizers' },
    { symbol: 'RCF.NS', name: 'Rashtriya Chemicals', sector: 'Chemicals' },
    { symbol: 'FACT.NS', name: 'Fact', sector: 'Fertilizers' },
    { symbol: 'GSFC.NS', name: 'Gujarat State Fertilizers', sector: 'Fertilizers' },
    { symbol: 'GNFC.NS', name: 'GNFC', sector: 'Chemicals' },
    { symbol: 'GAIL.NS', name: 'GAIL India', sector: 'Oil & Gas' },
    { symbol: 'HPCL.NS', name: 'HPCL', sector: 'Oil & Gas' },
    { symbol: 'IOC.NS', name: 'Indian Oil Corporation', sector: 'Oil & Gas' },
    { symbol: 'MRPL.NS', name: 'MRPL', sector: 'Oil & Gas' },
    { symbol: 'OIL.NS', name: 'Oil India', sector: 'Oil & Gas' },
    { symbol: 'PETRONET.NS', name: 'Petronet LNG', sector: 'Oil & Gas' },
    { symbol: 'GUJGAS.NS', name: 'Gujarat Gas', sector: 'Oil & Gas' },
    { symbol: 'MGL.NS', name: 'Mahanagar Gas', sector: 'Oil & Gas' },
    { symbol: 'IGL.NS', name: 'Indraprastha Gas', sector: 'Oil & Gas' },
    { symbol: 'AEGISCHEM.NS', name: 'Aegis Logistics', sector: 'Oil & Gas' },
    { symbol: 'CASTROLIND.NS', name: 'Castrol India', sector: 'Oil & Gas' },
    
    // Penny Stocks & Small Caps
    { symbol: 'RPOWER.NS', name: 'Reliance Power', sector: 'Power' },
    { symbol: 'RINFRA.NS', name: 'Reliance Infrastructure', sector: 'Infrastructure' },
    { symbol: 'RCOM.NS', name: 'Reliance Communications', sector: 'Telecom' },
    { symbol: 'DHFL.NS', name: 'Dewan Housing', sector: 'Finance' },
    { symbol: 'INFIBEAM.NS', name: 'Infibeam Avenues', sector: 'IT' },
    { symbol: 'ADANIGAS.NS', name: 'Adani Total Gas', sector: 'Oil & Gas' },
    { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy', sector: 'Power' },
    { symbol: 'ADANITRANS.NS', name: 'Adani Transmission', sector: 'Power' },
    { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements', sector: 'Cement' },
    { symbol: 'ACC.NS', name: 'ACC', sector: 'Cement' },
    { symbol: 'SHREECEM.NS', name: 'Shree Cement', sector: 'Cement' },
    { symbol: 'RAMCOCEM.NS', name: 'Ramco Cements', sector: 'Cement' },
    { symbol: 'JKCEMENT.NS', name: 'JK Cement', sector: 'Cement' },
    { symbol: 'DALBHARAT.NS', name: 'Dalmia Bharat', sector: 'Cement' },
    { symbol: 'HEIDELBERG.NS', name: 'HeidelbergCement India', sector: 'Cement' },
    { symbol: 'PRISMCEM.NS', name: 'Prism Johnson', sector: 'Cement' },
    { symbol: 'BIRLACORPN.NS', name: 'Birla Corporation', sector: 'Cement' },
    { symbol: 'JKPAPER.NS', name: 'JK Paper', sector: 'Paper' },
    { symbol: 'TNPL.NS', name: 'Tamil Nadu Newsprint', sector: 'Paper' },
    { symbol: 'WSTCSTPAPR.NS', name: 'West Coast Paper', sector: 'Paper' },
    
    // Auto Parts & Components
    { symbol: 'MOTHERSON.NS', name: 'Samvardhana Motherson', sector: 'Auto' },
    { symbol: 'BHARATFORG.NS', name: 'Bharat Forge', sector: 'Auto' },
    { symbol: 'ENDURANCE.NS', name: 'Endurance Technologies', sector: 'Auto' },
    { symbol: 'SUNDARMFIN.NS', name: 'Sundaram Finance', sector: 'Finance' },
    { symbol: 'SUNDARMBR.NS', name: 'Sundaram Brake', sector: 'Auto' },
    { symbol: 'SUBROS.NS', name: 'Subros', sector: 'Auto' },
    { symbol: 'MINDA.NS', name: 'Minda Corporation', sector: 'Auto' },
    { symbol: 'LUMAXTECH.NS', name: 'Lumax Auto', sector: 'Auto' },
    { symbol: 'VARROC.NS', name: 'Varroc Engineering', sector: 'Auto' },
    { symbol: 'SUPRAJIT.NS', name: 'Suprajit Engineering', sector: 'Auto' },
    { symbol: 'SWARAJENG.NS', name: 'Swaraj Engines', sector: 'Auto' },
    
    // Textiles
    { symbol: 'ARVIND.NS', name: 'Arvind', sector: 'Textiles' },
    { symbol: 'RAYMOND.NS', name: 'Raymond', sector: 'Textiles' },
    { symbol: 'PAGEIND.NS', name: 'Page Industries', sector: 'Textiles' },
    { symbol: 'MANYAVAR.NS', name: 'Vedant Fashions', sector: 'Textiles' },
    { symbol: 'TRENT.NS', name: 'Trent', sector: 'Retail' },
    { symbol: 'SHOPERSTOP.NS', name: 'Shoppers Stop', sector: 'Retail' },
    { symbol: 'BATA.NS', name: 'Bata India', sector: 'Footwear' },
    { symbol: 'RELAXO.NS', name: 'Relaxo Footwears', sector: 'Footwear' },
    { symbol: 'CAMPUS.NS', name: 'Campus Activewear', sector: 'Footwear' },
    { symbol: 'VSTIND.NS', name: 'VST Industries', sector: 'Tobacco' },
    { symbol: 'GODFRYPHLP.NS', name: 'Godfrey Phillips', sector: 'Tobacco' },
    
    // IT Services (Small/Mid)
    { symbol: 'MPHASIS.NS', name: 'Mphasis', sector: 'IT' },
    { symbol: 'COFORGE.NS', name: 'Coforge', sector: 'IT' },
    { symbol: 'PERSISTENT.NS', name: 'Persistent Systems', sector: 'IT' },
    { symbol: 'LTTS.NS', name: 'L&T Technology Services', sector: 'IT' },
    { symbol: 'CYIENT.NS', name: 'Cyient', sector: 'IT' },
    { symbol: 'MASTEK.NS', name: 'Mastek', sector: 'IT' },
    { symbol: 'MINDTREE.NS', name: 'Mindtree', sector: 'IT' },
    { symbol: 'NIIT.NS', name: 'NIIT', sector: 'IT' },
    { symbol: 'KPITTECH.NS', name: 'KPIT Technologies', sector: 'IT' },
    { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', sector: 'IT' },
    { symbol: 'ZENSAR.NS', name: 'Zensar Technologies', sector: 'IT' },
    { symbol: 'BIRLASOFT.NS', name: 'Birlasoft', sector: 'IT' },
    { symbol: 'SONATSOFTW.NS', name: 'Sonata Software', sector: 'IT' },
    { symbol: 'INTELLECT.NS', name: 'Intellect Design', sector: 'IT' },
    { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds', sector: 'IT' },
    { symbol: 'NEWGEN.NS', name: 'Newgen Software', sector: 'IT' },
    { symbol: 'DATAMATICS.NS', name: 'Datamatics', sector: 'IT' },
    { symbol: 'TANLA.NS', name: 'Tanla Platforms', sector: 'IT' },
    { symbol: 'ROUTE.NS', name: 'Route Mobile', sector: 'IT' },
    { symbol: 'LATENTVIEW.NS', name: 'Latent View', sector: 'IT' },
    { symbol: 'QUICKHEAL.NS', name: 'Quick Heal', sector: 'IT' },
    { symbol: 'AFFLE.NS', name: 'Affle India', sector: 'IT' },
    { symbol: 'NAZARA.NS', name: 'Nazara Technologies', sector: 'Gaming' },
    
    // Pharma (Small/Mid)
    { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma', sector: 'Pharma' },
    { symbol: 'LAURUS.NS', name: 'Laurus Labs', sector: 'Pharma' },
    { symbol: 'GRANULES.NS', name: 'Granules India', sector: 'Pharma' },
    { symbol: 'AJANTPHARM.NS', name: 'Ajanta Pharma', sector: 'Pharma' },
    { symbol: 'IPCALAB.NS', name: 'IPCA Laboratories', sector: 'Pharma' },
    { symbol: 'ALKEM.NS', name: 'Alkem Laboratories', sector: 'Pharma' },
    { symbol: 'GLAXO.NS', name: 'GlaxoSmithKline', sector: 'Pharma' },
    { symbol: 'PFIZER.NS', name: 'Pfizer', sector: 'Pharma' },
    { symbol: 'SANOFI.NS', name: 'Sanofi India', sector: 'Pharma' },
    { symbol: 'ABBOTINDIA.NS', name: 'Abbott India', sector: 'Pharma' },
    { symbol: 'GLENMARK.NS', name: 'Glenmark Pharma', sector: 'Pharma' },
    { symbol: 'BIOCON.NS', name: 'Biocon', sector: 'Pharma' },
    { symbol: 'ZYDUSLIFE.NS', name: 'Zydus Lifesciences', sector: 'Pharma' },
    { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharma', sector: 'Pharma' },
    { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma', sector: 'Pharma' },
    { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', sector: 'Healthcare' },
    { symbol: 'MAXHEALTH.NS', name: 'Max Healthcare', sector: 'Healthcare' },
    { symbol: 'FORTIS.NS', name: 'Fortis Healthcare', sector: 'Healthcare' },
    { symbol: 'NARAYANA.NS', name: 'Narayana Hrudayalaya', sector: 'Healthcare' },
    { symbol: 'METROPOLIS.NS', name: 'Metropolis Healthcare', sector: 'Healthcare' },
    { symbol: 'LALPATHLAB.NS', name: 'Dr Lal PathLabs', sector: 'Healthcare' },
    { symbol: 'THYROCARE.NS', name: 'Thyrocare Technologies', sector: 'Healthcare' },
    
    // Finance & NBFC
    { symbol: 'M&MFIN.NS', name: 'Mahindra Finance', sector: 'Finance' },
    { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Finance', sector: 'Finance' },
    { symbol: 'LICHSGFIN.NS', name: 'LIC Housing Finance', sector: 'Finance' },
    { symbol: 'CANFINHOME.NS', name: 'Can Fin Homes', sector: 'Finance' },
    { symbol: 'HOMEFIRST.NS', name: 'Home First Finance', sector: 'Finance' },
    { symbol: 'APTUS.NS', name: 'Aptus Value Housing', sector: 'Finance' },
    { symbol: 'AAVAS.NS', name: 'Aavas Financiers', sector: 'Finance' },
    { symbol: 'POONAWALLA.NS', name: 'Poonawalla Fincorp', sector: 'Finance' },
    { symbol: 'L&TFH.NS', name: 'L&T Finance', sector: 'Finance' },
    { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance', sector: 'Finance' },
    { symbol: 'MANAPPURAM.NS', name: 'Manappuram Finance', sector: 'Finance' },
    { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', sector: 'Finance' },
    { symbol: 'CREDITACC.NS', name: 'CreditAccess Grameen', sector: 'Finance' },
    { symbol: 'SPANDANA.NS', name: 'Spandana Sphoorty', sector: 'Finance' },
    { symbol: 'FUSION.NS', name: 'Fusion Microfinance', sector: 'Finance' },
    { symbol: 'UJJIVANSFB.NS', name: 'Ujjivan Small Finance', sector: 'Banking' },
    { symbol: 'EQUITASBNK.NS', name: 'Equitas Small Finance', sector: 'Banking' },
    { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank', sector: 'Banking' },
    { symbol: 'PAYTM.NS', name: 'One 97 Communications', sector: 'Fintech' },
    { symbol: 'POLICYBZR.NS', name: 'PB Fintech', sector: 'Fintech' },
    
    // Insurance
    { symbol: 'LICI.NS', name: 'Life Insurance Corp', sector: 'Insurance' },
    { symbol: 'NIACL.NS', name: 'New India Assurance', sector: 'Insurance' },
    { symbol: 'GICRE.NS', name: 'General Insurance Corp', sector: 'Insurance' },
    { symbol: 'ICICIGI.NS', name: 'ICICI Lombard', sector: 'Insurance' },
    { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life', sector: 'Insurance' },
    { symbol: 'STARHEALTH.NS', name: 'Star Health Insurance', sector: 'Insurance' },
    
    // Real Estate
    { symbol: 'DLF.NS', name: 'DLF', sector: 'Real Estate' },
    { symbol: 'GODREJPROP.NS', name: 'Godrej Properties', sector: 'Real Estate' },
    { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty', sector: 'Real Estate' },
    { symbol: 'PRESTIGE.NS', name: 'Prestige Estates', sector: 'Real Estate' },
    { symbol: 'SOBHA.NS', name: 'Sobha', sector: 'Real Estate' },
    { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises', sector: 'Real Estate' },
    { symbol: 'LODHA.NS', name: 'Macrotech Developers', sector: 'Real Estate' },
    { symbol: 'PHOENIXLTD.NS', name: 'Phoenix Mills', sector: 'Real Estate' },
    { symbol: 'MAHLIFE.NS', name: 'Mahindra Lifespace', sector: 'Real Estate' },
    { symbol: 'SUNTECK.NS', name: 'Sunteck Realty', sector: 'Real Estate' },
    { symbol: 'KOLTEPATIL.NS', name: 'Kolte Patil', sector: 'Real Estate' },
    { symbol: 'ASHIANA.NS', name: 'Ashiana Housing', sector: 'Real Estate' },
    
    // Hotels & Tourism
    { symbol: 'INDHOTEL.NS', name: 'Indian Hotels', sector: 'Hotels' },
    { symbol: 'LEMON.NS', name: 'Lemon Tree Hotels', sector: 'Hotels' },
    { symbol: 'EIHOTEL.NS', name: 'EIH', sector: 'Hotels' },
    { symbol: 'CHALET.NS', name: 'Chalet Hotels', sector: 'Hotels' },
    { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks', sector: 'QSR' },
    { symbol: 'DEVYANI.NS', name: 'Devyani International', sector: 'QSR' },
    { symbol: 'SAPPHIRE.NS', name: 'Sapphire Foods', sector: 'QSR' },
    { symbol: 'WESTLIFE.NS', name: 'Westlife Foodworld', sector: 'QSR' },
    { symbol: 'BARBEQUE.NS', name: 'Barbeque Nation', sector: 'QSR' },
    { symbol: 'ZOMATO.NS', name: 'Zomato', sector: 'Food Tech' },
    { symbol: 'SWIGGYFOOD.NS', name: 'Swiggy', sector: 'Food Tech' },
    
    // Media & Entertainment
    { symbol: 'PVRINOX.NS', name: 'PVR Inox', sector: 'Entertainment' },
    { symbol: 'TV18BRDCST.NS', name: 'TV18 Broadcast', sector: 'Media' },
    { symbol: 'NETWORK18.NS', name: 'Network18 Media', sector: 'Media' },
    { symbol: 'SUNTV.NS', name: 'Sun TV Network', sector: 'Media' },
    { symbol: 'ZEEL.NS', name: 'Zee Entertainment', sector: 'Media' },
    { symbol: 'TIPS.NS', name: 'Tips Industries', sector: 'Entertainment' },
    { symbol: 'SAREGAMA.NS', name: 'Saregama India', sector: 'Entertainment' },
    
    // Power & Utilities (Extended)
    { symbol: 'TATAPOWER.NS', name: 'Tata Power', sector: 'Power' },
    { symbol: 'ADANIPOWER.NS', name: 'Adani Power', sector: 'Power' },
    { symbol: 'POWERGRID.NS', name: 'Power Grid Corp', sector: 'Power' },
    { symbol: 'NTPC.NS', name: 'NTPC', sector: 'Power' },
    { symbol: 'TORNTPOWER.NS', name: 'Torrent Power', sector: 'Power' },
    { symbol: 'CESC.NS', name: 'CESC', sector: 'Power' },
    { symbol: 'JSL.NS', name: 'Jindal SAW', sector: 'Steel' },
    { symbol: 'WELSPUNIND.NS', name: 'Welspun India', sector: 'Textiles' },
    { symbol: 'PEL.NS', name: 'Piramal Enterprises', sector: 'Diversified' },
    { symbol: 'GODREJCP.NS', name: 'Godrej Consumer', sector: 'FMCG' },
    { symbol: 'GODREJIND.NS', name: 'Godrej Industries', sector: 'Diversified' },
    { symbol: 'MARICO.NS', name: 'Marico', sector: 'FMCG' },
    { symbol: 'DABUR.NS', name: 'Dabur India', sector: 'FMCG' },
    { symbol: 'EMAMILTD.NS', name: 'Emami', sector: 'FMCG' },
    { symbol: 'COLPAL.NS', name: 'Colgate-Palmolive', sector: 'FMCG' },
    { symbol: 'PGHH.NS', name: 'Procter & Gamble', sector: 'FMCG' },
    { symbol: 'GILLETTE.NS', name: 'Gillette India', sector: 'FMCG' },
    { symbol: 'RADICO.NS', name: 'Radico Khaitan', sector: 'Beverages' },
    { symbol: 'UNITDSPR.NS', name: 'United Spirits', sector: 'Beverages' },
    { symbol: 'UBL.NS', name: 'United Breweries', sector: 'Beverages' },
    { symbol: 'VBL.NS', name: 'Varun Beverages', sector: 'Beverages' },
    { symbol: 'TATACONS.NS', name: 'Tata Consumer', sector: 'FMCG' },
    
    // E-commerce & Consumer Internet
    { symbol: 'NYKAA.NS', name: 'FSN E-Commerce', sector: 'E-commerce' },
    { symbol: 'DELHIVERY.NS', name: 'Delhivery', sector: 'Logistics' },
    { symbol: 'CARTRADE.NS', name: 'CarTrade Tech', sector: 'E-commerce' },
    { symbol: 'EASEMYTRIP.NS', name: 'Easy Trip Planners', sector: 'Travel' },
    { symbol: 'RATEGAIN.NS', name: 'RateGain Travel', sector: 'Travel Tech' },
    { symbol: 'MAPMYINDIA.NS', name: 'CE Info Systems', sector: 'IT' },
    { symbol: 'INDIAMART.NS', name: 'Indiamart Intermesh', sector: 'E-commerce' },
    { symbol: 'JUSTDIAL.NS', name: 'Just Dial', sector: 'IT' },
    { symbol: 'INFOEDGE.NS', name: 'Info Edge', sector: 'IT' },
    
    // Defence
    { symbol: 'HAL.NS', name: 'Hindustan Aeronautics', sector: 'Defence' },
    { symbol: 'BEL.NS', name: 'Bharat Electronics', sector: 'Defence' },
    { symbol: 'BDL.NS', name: 'Bharat Dynamics', sector: 'Defence' },
    { symbol: 'BEML.NS', name: 'BEML', sector: 'Capital Goods' },
    { symbol: 'GRSE.NS', name: 'Garden Reach Shipbuilders', sector: 'Defence' },
    { symbol: 'COCHINSHIP.NS', name: 'Cochin Shipyard', sector: 'Defence' },
    { symbol: 'MAZAGON.NS', name: 'Mazagon Dock', sector: 'Defence' },
    { symbol: 'MIDHANI.NS', name: 'MIDHANI', sector: 'Defence' },
    { symbol: 'DATAPATTNS.NS', name: 'Data Patterns', sector: 'Defence' },
    { symbol: 'PARAS.NS', name: 'Paras Defence', sector: 'Defence' },
    { symbol: 'ASTRA.NS', name: 'Astra Microwave', sector: 'Defence' },
    
    // Capital Goods & Engineering
    { symbol: 'SIEMENS.NS', name: 'Siemens', sector: 'Capital Goods' },
    { symbol: 'ABB.NS', name: 'ABB India', sector: 'Capital Goods' },
    { symbol: 'HAVELLS.NS', name: 'Havells India', sector: 'Consumer Durables' },
    { symbol: 'VOLTAS.NS', name: 'Voltas', sector: 'Consumer Durables' },
    { symbol: 'BLUESTAR.NS', name: 'Blue Star', sector: 'Consumer Durables' },
    { symbol: 'CROMPTON.NS', name: 'Crompton Greaves', sector: 'Consumer Durables' },
    { symbol: 'WHIRLPOOL.NS', name: 'Whirlpool', sector: 'Consumer Durables' },
    { symbol: 'DIXON.NS', name: 'Dixon Technologies', sector: 'Electronics' },
    { symbol: 'AMBER.NS', name: 'Amber Enterprises', sector: 'Electronics' },
    { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics', sector: 'Building Materials' },
    { symbol: 'CERA.NS', name: 'Cera Sanitaryware', sector: 'Building Materials' },
    { symbol: 'ASTRAL.NS', name: 'Astral', sector: 'Pipes' },
    { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries', sector: 'Pipes' },
    { symbol: 'PRINCEPIPE.NS', name: 'Prince Pipes', sector: 'Pipes' },
    { symbol: 'POLYCAB.NS', name: 'Polycab India', sector: 'Cables' },
    { symbol: 'KEI.NS', name: 'KEI Industries', sector: 'Cables' },
    { symbol: 'APLAPOLLO.NS', name: 'APL Apollo Tubes', sector: 'Steel' },
    { symbol: 'RATNAMANI.NS', name: 'Ratnamani Metals', sector: 'Steel' },
    
    // Metals & Mining (Extended)
    { symbol: 'TATASTEEL.NS', name: 'Tata Steel', sector: 'Steel' },
    { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', sector: 'Steel' },
    { symbol: 'SAIL.NS', name: 'Steel Authority', sector: 'Steel' },
    { symbol: 'HINDZINC.NS', name: 'Hindustan Zinc', sector: 'Mining' },
    { symbol: 'VEDL.NS', name: 'Vedanta', sector: 'Mining' },
    { symbol: 'HINDALCO.NS', name: 'Hindalco', sector: 'Aluminium' },
    { symbol: 'NATIONALUM.NS', name: 'National Aluminium', sector: 'Aluminium' },
    { symbol: 'MOIL.NS', name: 'MOIL', sector: 'Mining' },
    { symbol: 'WELCORP.NS', name: 'Welspun Corp', sector: 'Steel' },
    { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel', sector: 'Steel' },
    
    // Chemicals & Specialty Chemicals
    { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries', sector: 'Chemicals' },
    { symbol: 'BERGERPAINTS.NS', name: 'Berger Paints', sector: 'Paints' },
    { symbol: 'KANSAINER.NS', name: 'Kansai Nerolac', sector: 'Paints' },
    { symbol: 'INDIGO.NS', name: 'Indigo Paints', sector: 'Paints' },
    { symbol: 'ATUL.NS', name: 'Atul', sector: 'Chemicals' },
    { symbol: 'DEEPAKFERT.NS', name: 'Deepak Fertilisers', sector: 'Chemicals' },
    { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite', sector: 'Chemicals' },
    { symbol: 'FLUOROCHEM.NS', name: 'Gujarat Fluorochemicals', sector: 'Chemicals' },
    { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine', sector: 'Chemicals' },
    { symbol: 'SRF.NS', name: 'SRF', sector: 'Chemicals' },
    { symbol: 'CLEAN.NS', name: 'Clean Science', sector: 'Chemicals' },
    { symbol: 'FINEORG.NS', name: 'Fine Organic', sector: 'Chemicals' },
    { symbol: 'VINATIORGA.NS', name: 'Vinati Organics', sector: 'Chemicals' },
    { symbol: 'ALKYLAMINE.NS', name: 'Alkyl Amines', sector: 'Chemicals' },
    { symbol: 'TATACHEM.NS', name: 'Tata Chemicals', sector: 'Chemicals' },
    { symbol: 'NOCIL.NS', name: 'NOCIL', sector: 'Chemicals' },
    { symbol: 'BALRAMCHIN.NS', name: 'Balrampur Chini', sector: 'Sugar' },
    { symbol: 'RENUKA.NS', name: 'Shree Renuka Sugars', sector: 'Sugar' },
    { symbol: 'TRIVENI.NS', name: 'Triveni Engineering', sector: 'Sugar' },
    { symbol: 'DWARIKESH.NS', name: 'Dwarikesh Sugar', sector: 'Sugar' },
    
    // Logistics & Supply Chain
    { symbol: 'CONCOR.NS', name: 'Container Corp', sector: 'Logistics' },
    { symbol: 'BLUEDART.NS', name: 'Blue Dart Express', sector: 'Logistics' },
    { symbol: 'ALLCARGO.NS', name: 'Allcargo Logistics', sector: 'Logistics' },
    { symbol: 'TCI.NS', name: 'Transport Corp', sector: 'Logistics' },
    { symbol: 'GATI.NS', name: 'Gati', sector: 'Logistics' },
    { symbol: 'VRL.NS', name: 'VRL Logistics', sector: 'Logistics' },
    { symbol: 'MAHLOG.NS', name: 'Mahindra Logistics', sector: 'Logistics' },
    { symbol: 'GATEWAY.NS', name: 'Gateway Distriparks', sector: 'Logistics' },
    
    // Aviation
    { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation', sector: 'Aviation' },
    { symbol: 'SPICEJET.NS', name: 'SpiceJet', sector: 'Aviation' },
    { symbol: 'GMRAIR.NS', name: 'GMR Airports', sector: 'Aviation' },
    
    // Miscellaneous & Diversified
    { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto', sector: 'Automobile' },
    { symbol: 'BOSCHLTD.NS', name: 'Bosch', sector: 'Auto Parts' },
    { symbol: 'CUMMINSIND.NS', name: 'Cummins India', sector: 'Capital Goods' },
    { symbol: 'ESCORTS.NS', name: 'Escort Kubota', sector: 'Tractors' },
    { symbol: 'TATVA.NS', name: 'Tatva Chintan', sector: 'Chemicals' },
    { symbol: 'HGINFRA.NS', name: 'H.G. Infra', sector: 'Infrastructure' },
    { symbol: 'PNCINFRA.NS', name: 'PNC Infratech', sector: 'Infrastructure' },
    { symbol: 'KPIL.NS', name: 'Kalpataru Projects', sector: 'Infrastructure' },
    { symbol: 'JAINS.NS', name: 'Jain Irrigation', sector: 'Agriculture' },
    { symbol: 'UPL.NS', name: 'UPL', sector: 'Agrochemicals' },
    { symbol: 'PI.NS', name: 'PI Industries', sector: 'Agrochemicals' },
    { symbol: 'RALLIS.NS', name: 'Rallis India', sector: 'Agrochemicals' },
    { symbol: 'SUMICHEM.NS', name: 'Sumitomo Chemical', sector: 'Agrochemicals' },
    { symbol: 'BAYER.NS', name: 'Bayer CropScience', sector: 'Agrochemicals' },
    { symbol: 'BASF.NS', name: 'BASF India', sector: 'Chemicals' },
    { symbol: 'AKZOINDIA.NS', name: 'AkzoNobel India', sector: 'Paints' },
    { symbol: '3MINDIA.NS', name: '3M India', sector: 'Diversified' },
    { symbol: 'HONAUT.NS', name: 'Honeywell Automation', sector: 'Capital Goods' },
    { symbol: 'THERMAX.NS', name: 'Thermax', sector: 'Capital Goods' },
    { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton', sector: 'Capital Goods' },
    { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal', sector: 'Capital Goods' },
    { symbol: 'SCHAEFFLER.NS', name: 'Schaeffler India', sector: 'Bearings' },
    { symbol: 'SKFIND.NS', name: 'SKF India', sector: 'Bearings' },
    { symbol: 'TIMKEN.NS', name: 'Timken India', sector: 'Bearings' },
    { symbol: 'NRB.NS', name: 'NRB Bearings', sector: 'Bearings' },
    
    // Entertainment & Gaming
    { symbol: 'GAMEINFIN.NS', name: 'Gameinfin', sector: 'Gaming' },
    { symbol: 'NAZARA.NS', name: 'Nazara Technologies', sector: 'Gaming' },
    { symbol: 'DELTACORP.NS', name: 'Delta Corp', sector: 'Gaming' },
    
    // Education
    { symbol: 'APARINDS.NS', name: 'Apar Industries', sector: 'Education' },
    { symbol: 'NAVNETEDUL.NS', name: 'Navneet Education', sector: 'Education' },
    { symbol: 'SIS.NS', name: 'SIS', sector: 'Security Services' },
    { symbol: 'TEAMLEASE.NS', name: 'TeamLease Services', sector: 'Staffing' },
    { symbol: 'QUESS.NS', name: 'Quess Corp', sector: 'Staffing' },
    
    // More Small/Micro Caps & Penny Stocks
    { symbol: 'GTPL.NS', name: 'GTPL Hathway', sector: 'Media' },
    { symbol: 'HATHWAY.NS', name: 'Hathway Cable', sector: 'Media' },
    { symbol: 'DEN.NS', name: 'Den Networks', sector: 'Media' },
    { symbol: 'MTNL.NS', name: 'MTNL', sector: 'Telecom' },
    { symbol: 'ITI.NS', name: 'ITI', sector: 'Telecom' },
    { symbol: 'HFCL.NS', name: 'HFCL', sector: 'Telecom' },
    { symbol: 'STLTECH.NS', name: 'Sterlite Technologies', sector: 'Telecom' },
    { symbol: 'TEJAS.NS', name: 'Tejas Networks', sector: 'Telecom' },
    { symbol: 'CYBERTECH.NS', name: 'CyberTech Systems', sector: 'IT' },
    { symbol: 'GTLINFRA.NS', name: 'GTL Infrastructure', sector: 'Telecom' },
    { symbol: 'RTNPOWER.NS', name: 'RattanIndia Power', sector: 'Power' },
    { symbol: 'JPASSOCIAT.NS', name: 'Jaiprakash Associates', sector: 'Infrastructure' },
    { symbol: 'JPPOWER.NS', name: 'Jaiprakash Power', sector: 'Power' },
    { symbol: 'UNITECH.NS', name: 'Unitech', sector: 'Real Estate' },
    { symbol: 'SUZLON.NS', name: 'Suzlon Energy', sector: 'Power' },
    { symbol: 'RELINFRA.NS', name: 'Reliance Infra', sector: 'Infrastructure' },
    { symbol: 'RCOM.NS', name: 'Reliance Communications', sector: 'Telecom' },
    { symbol: 'RELCAPITAL.NS', name: 'Reliance Capital', sector: 'Finance' },
    { symbol: 'IBREALEST.NS', name: 'Indiabulls Real Estate', sector: 'Real Estate' },
    { symbol: 'IBHFL.NS', name: 'Indiabulls Housing', sector: 'Finance' },
    
    // Shipping & Ports
    { symbol: 'SCI.NS', name: 'Shipping Corp', sector: 'Shipping' },
    { symbol: 'GESHIP.NS', name: 'Great Eastern Shipping', sector: 'Shipping' },
    
    // Brokerage & Asset Management
    { symbol: 'MCX.NS', name: 'MCX India', sector: 'Exchange' },
    { symbol: 'BSE.NS', name: 'BSE', sector: 'Exchange' },
    { symbol: 'CDSL.NS', name: 'CDSL', sector: 'Depository' },
    { symbol: 'CAMS.NS', name: 'Computer Age Mgmt', sector: 'Asset Management' },
    { symbol: 'KFINTECH.NS', name: 'KFin Technologies', sector: 'Asset Management' },
    { symbol: 'MOTILALOFS.NS', name: 'Motilal Oswal', sector: 'Brokerage' },
    { symbol: 'EDELWEISS.NS', name: 'Edelweiss Financial', sector: 'Finance' },
    { symbol: 'ANGELONE.NS', name: 'Angel One', sector: 'Brokerage' },
    { symbol: 'FIVESTAR.NS', name: '5paisa Capital', sector: 'Brokerage' },
    
    // PSU Banks (Extended)
    { symbol: 'PNB.NS', name: 'Punjab National Bank', sector: 'Banking' },
    { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda', sector: 'Banking' },
    { symbol: 'IOB.NS', name: 'Indian Overseas Bank', sector: 'Banking' },
    { symbol: 'CANBK.NS', name: 'Canara Bank', sector: 'Banking' },
    { symbol: 'BANKINDIA.NS', name: 'Bank of India', sector: 'Banking' },
    { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra', sector: 'Banking' },
    { symbol: 'UCOBANK.NS', name: 'UCO Bank', sector: 'Banking' },
    { symbol: 'CENTRALBK.NS', name: 'Central Bank', sector: 'Banking' },
    { symbol: 'UNIONBANK.NS', name: 'Union Bank', sector: 'Banking' },
    { symbol: 'INDIANB.NS', name: 'Indian Bank', sector: 'Banking' },
    { symbol: 'PSB.NS', name: 'Punjab & Sind Bank', sector: 'Banking' },
    { symbol: 'J&KBANK.NS', name: 'J&K Bank', sector: 'Banking' },
    { symbol: 'SOUTHBANK.NS', name: 'South Indian Bank', sector: 'Banking' },
    { symbol: 'KARURVYSYA.NS', name: 'Karur Vysya Bank', sector: 'Banking' },
    { symbol: 'CUB.NS', name: 'City Union Bank', sector: 'Banking' },
    { symbol: 'DCBBANK.NS', name: 'DCB Bank', sector: 'Banking' },
    { symbol: 'DHANI.NS', name: 'Dhani Services', sector: 'Finance' },
    
    // Textile Machinery & Equipment
    { symbol: 'LAKSHVILAS.NS', name: 'Lakshmi Machine', sector: 'Textiles' },
    
    // Gems & Jewellery
    { symbol: 'TITAN.NS', name: 'Titan Company', sector: 'Jewellery' },
    { symbol: 'KALYAN.NS', name: 'Kalyan Jewellers', sector: 'Jewellery' },
    { symbol: 'SENCO.NS', name: 'Senco Gold', sector: 'Jewellery' },
    { symbol: 'THANGAMAYL.NS', name: 'Thangamayil', sector: 'Jewellery' },
    { symbol: 'PCJEWELLER.NS', name: 'PC Jeweller', sector: 'Jewellery' },
    { symbol: 'RAJESHEXPO.NS', name: 'Rajesh Exports', sector: 'Jewellery' },
    { symbol: 'TRIGOLD.NS', name: 'Tribhovandas Bhimji', sector: 'Jewellery' },
    
    // ============================================
    // NSE SME STOCKS (Small & Medium Enterprises)
    // ============================================
    { symbol: 'AHIMSA.NS', name: 'Ahimsa Industries', sector: 'SME' },
    { symbol: 'AIROLAM.NS', name: 'Airolam', sector: 'SME' },
    { symbol: 'AKSHARCHEM.NS', name: 'Akshar Chem India', sector: 'Chemicals' },
    { symbol: 'ALFREDHER.NS', name: 'Alfred Herbert', sector: 'Capital Goods' },
    { symbol: 'ALICON.NS', name: 'Alicon Castalloy', sector: 'Auto Parts' },
    { symbol: 'ALKALI.NS', name: 'Alkali Metals', sector: 'Chemicals' },
    { symbol: 'ALMONDZ.NS', name: 'Almondz Global', sector: 'Finance' },
    { symbol: 'ALPA.NS', name: 'Alpa Laboratories', sector: 'Pharma' },
    { symbol: 'AMARAJABAT.NS', name: 'Amara Raja Batteries', sector: 'Auto Parts' },
    { symbol: 'AMDIND.NS', name: 'AMD Industries', sector: 'Packaging' },
    { symbol: 'AMIORG.NS', name: 'Ami Organics', sector: 'Chemicals' },
    { symbol: 'ANIK.NS', name: 'Anik Industries', sector: 'SME' },
    { symbol: 'ANKITMETAL.NS', name: 'Ankit Metal', sector: 'Metals' },
    { symbol: 'ANNAPURNA.NS', name: 'Annapurna Finance', sector: 'Finance' },
    { symbol: 'ANUP.NS', name: 'Anup Engineering', sector: 'Capital Goods' },
    { symbol: 'APCL.NS', name: 'Anjani Portland', sector: 'Cement' },
    { symbol: 'APEX.NS', name: 'Apex Frozen Foods', sector: 'Food' },
    { symbol: 'APOLLO.NS', name: 'Apollo Micro Systems', sector: 'Defence' },
    { symbol: 'APTECHT.NS', name: 'Aptech', sector: 'Education' },
    { symbol: 'ARCHIDPLY.NS', name: 'Archidply Industries', sector: 'Building Materials' },
    { symbol: 'ARCN.NS', name: 'Arcotech', sector: 'Metals' },
    { symbol: 'ARIHANT.NS', name: 'Arihant Capital', sector: 'Finance' },
    { symbol: 'ARIHANTCAP.NS', name: 'Arihant Capital Markets', sector: 'Finance' },
    { symbol: 'AROGRANITE.NS', name: 'Aro Granite', sector: 'Building Materials' },
    { symbol: 'ARROWGREEN.NS', name: 'Arrow Greentech', sector: 'Plastics' },
    { symbol: 'ARROWHEAD.NS', name: 'Arrowhead Seperation', sector: 'Industrial' },
    { symbol: 'ARSS.NS', name: 'ARSS Infrastructure', sector: 'Infrastructure' },
    { symbol: 'ARVEE.NS', name: 'Arvee Laboratories', sector: 'Pharma' },
    { symbol: 'ASHAPURA.NS', name: 'Ashapura Minechem', sector: 'Mining' },
    { symbol: 'ASHIANA.NS', name: 'Ashiana Housing', sector: 'Real Estate' },
    { symbol: 'ASHOKA.NS', name: 'Ashoka Buildcon', sector: 'Infrastructure' },
    { symbol: 'ASHOKAMET.NS', name: 'Ashoka Metcast', sector: 'Engineering' },
    { symbol: 'ASIL.NS', name: 'Astral Poly', sector: 'Pipes' },
    { symbol: 'ASTERDM.NS', name: 'Aster DM Healthcare', sector: 'Healthcare' },
    { symbol: 'ASTRAZEN.NS', name: 'AstraZeneca Pharma', sector: 'Pharma' },
    { symbol: 'ATFL.NS', name: 'Agro Tech Foods', sector: 'FMCG' },
    { symbol: 'ATHARVENT.NS', name: 'Atharv Enterprises', sector: 'SME' },
    { symbol: 'ATLANTAA.NS', name: 'Atlanta', sector: 'Infrastructure' },
    { symbol: 'ATLASCYCLE.NS', name: 'Atlas Cycles', sector: 'Consumer' },
    { symbol: 'ATNINTER.NS', name: 'ATN International', sector: 'IT' },
    { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank', sector: 'Banking' },
    { symbol: 'AURIONPRO.NS', name: 'Aurionpro Solutions', sector: 'IT' },
    { symbol: 'AURUM.NS', name: 'Aurum PropTech', sector: 'Real Estate' },
    { symbol: 'AUTOIND.NS', name: 'Automotive Stampings', sector: 'Auto Parts' },
    { symbol: 'AVANTI.NS', name: 'Avanti Feeds', sector: 'Food' },
    { symbol: 'AVG.NS', name: 'AVG Logistics', sector: 'Logistics' },
    { symbol: 'AVONMORE.NS', name: 'Avonmore Capital', sector: 'Finance' },
    { symbol: 'AXISTECH.NS', name: 'Axiscades Tech', sector: 'IT' },
    { symbol: 'AXITA.NS', name: 'Axita Cotton', sector: 'Textiles' },
    
    // More SME Stocks (B-C)
    { symbol: 'BAGFILMS.NS', name: 'BAG Films', sector: 'Media' },
    { symbol: 'BAJAJCON.NS', name: 'Bajaj Consumer Care', sector: 'FMCG' },
    { symbol: 'BAJAJHIND.NS', name: 'Bajaj Hindusthan Sugar', sector: 'Sugar' },
    { symbol: 'BALAMINES.NS', name: 'Balaji Amines', sector: 'Chemicals' },
    { symbol: 'BALAXI.NS', name: 'Balaxi Pharmaceuticals', sector: 'Pharma' },
    { symbol: 'BALKRISHNA.NS', name: 'Balkrishna Industries', sector: 'Tyres' },
    { symbol: 'BALMLAWRIE.NS', name: 'Balmer Lawrie', sector: 'Diversified' },
    { symbol: 'BANARISUG.NS', name: 'Bannari Amman Sugars', sector: 'Sugar' },
    { symbol: 'BANCOINDIA.NS', name: 'Banco Products', sector: 'Auto Parts' },
    { symbol: 'BANG.NS', name: 'Bang Overseas', sector: 'Textiles' },
    { symbol: 'BANKBEES.NS', name: 'Bank ETF', sector: 'ETF' },
    { symbol: 'BARODARY.NS', name: 'Baroda Rayon', sector: 'Textiles' },
    { symbol: 'BASML.NS', name: 'BASML', sector: 'Rice' },
    { symbol: 'BAYERCROP.NS', name: 'Bayer CropScience', sector: 'Agrochemicals' },
    { symbol: 'BBL.NS', name: 'Bharat Bijlee', sector: 'Capital Goods' },
    { symbol: 'BCONCEPTS.NS', name: 'Brand Concepts', sector: 'Retail' },
    { symbol: 'BEARDSELL.NS', name: 'Beardsell', sector: 'Building Materials' },
    { symbol: 'BECTORFOOD.NS', name: 'Bector Food', sector: 'FMCG' },
    { symbol: 'BEDMUTHA.NS', name: 'Bedmutha Industries', sector: 'Metals' },
    { symbol: 'BELL.NS', name: 'Bell Fintec', sector: 'Finance' },
    { symbol: 'BEPL.NS', name: 'Bhansali Engineering', sector: 'Chemicals' },
    { symbol: 'BGRENERGY.NS', name: 'BGR Energy', sector: 'Capital Goods' },
    { symbol: 'BHAGERIA.NS', name: 'Bhageria Industries', sector: 'Chemicals' },
    { symbol: 'BHAGCHEM.NS', name: 'Bhagynagar Properties', sector: 'Real Estate' },
    { symbol: 'BHARATGEAR.NS', name: 'Bharat Gears', sector: 'Auto Parts' },
    { symbol: 'BHARATRAS.NS', name: 'Bharat Rasayan', sector: 'Chemicals' },
    { symbol: 'BHARATWIRE.NS', name: 'Bharat Wire Ropes', sector: 'Capital Goods' },
    { symbol: 'BIGBLOC.NS', name: 'Big Bloc Construction', sector: 'Real Estate' },
    { symbol: 'BINDALAGRO.NS', name: 'Bindal Agro Chem', sector: 'Agrochemicals' },
    { symbol: 'BIOCON.NS', name: 'Biocon', sector: 'Pharma' },
    { symbol: 'BIOPAC.NS', name: 'Biopac India', sector: 'Packaging' },
    { symbol: 'BIRLAMONEY.NS', name: 'Birlamoney', sector: 'Finance' },
    { symbol: 'BIRLACABLE.NS', name: 'Birla Cable', sector: 'Cables' },
    { symbol: 'BKV.NS', name: 'BKV Industries', sector: 'Textiles' },
    { symbol: 'BLISSGVS.NS', name: 'Bliss GVS Pharma', sector: 'Pharma' },
    { symbol: 'BLKASHYAP.NS', name: 'B L Kashyap', sector: 'Infrastructure' },
    { symbol: 'BLS.NS', name: 'BLS International', sector: 'Services' },
    { symbol: 'BODAL.NS', name: 'Bodal Chemicals', sector: 'Chemicals' },
    { symbol: 'BOHRAIND.NS', name: 'Bohra Industries', sector: 'Textiles' },
    { symbol: 'BOMBSHELL.NS', name: 'Bombshell Tube', sector: 'Engineering' },
    { symbol: 'BOMBARDIER.NS', name: 'Bombardier', sector: 'Railways' },
    { symbol: 'BORORENEW.NS', name: 'Borosil Renewables', sector: 'Power' },
    { symbol: 'BOROLTD.NS', name: 'Borosil', sector: 'Consumer' },
    { symbol: 'BRFL.NS', name: 'Ester Industries', sector: 'Packaging' },
    { symbol: 'BROOKS.NS', name: 'Brooks Laboratories', sector: 'Pharma' },
    { symbol: 'BSL.NS', name: 'BSL', sector: 'Textiles' },
    { symbol: 'BURNPUR.NS', name: 'Burnpur Cement', sector: 'Cement' },
    { symbol: 'BWL.NS', name: 'Bharat Wire Ropes', sector: 'Manufacturing' },
    
    // SME Stocks (C-D)
    { symbol: 'CALSOFT.NS', name: 'California Software', sector: 'IT' },
    { symbol: 'CAMLINFINE.NS', name: 'Camlin Fine Sciences', sector: 'Chemicals' },
    { symbol: 'CAMS.NS', name: 'Computer Age Management', sector: 'Finance' },
    { symbol: 'CANFINHOME.NS', name: 'Can Fin Homes', sector: 'Finance' },
    { symbol: 'CANTABIL.NS', name: 'Cantabil Retail', sector: 'Retail' },
    { symbol: 'CAPFIRST.NS', name: 'Capital First', sector: 'Finance' },
    { symbol: 'CAPLIPOINT.NS', name: 'Caplin Point Labs', sector: 'Pharma' },
    { symbol: 'CAPTRUST.NS', name: 'Capital Trust', sector: 'Finance' },
    { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal', sector: 'Capital Goods' },
    { symbol: 'CARERATING.NS', name: 'CARE Ratings', sector: 'Finance' },
    { symbol: 'CARYSIL.NS', name: 'Carysil', sector: 'Consumer' },
    { symbol: 'CASTECH.NS', name: 'Cascade Technologies', sector: 'IT' },
    { symbol: 'CATERPILLAR.NS', name: 'Caterpillar', sector: 'Capital Goods' },
    { symbol: 'CCHHL.NS', name: 'Country Club Hospitality', sector: 'Hotels' },
    { symbol: 'CCL.NS', name: 'CCL Products', sector: 'FMCG' },
    { symbol: 'CDSL.NS', name: 'CDSL', sector: 'Finance' },
    { symbol: 'CEBBCO.NS', name: 'CEBBCO', sector: 'Chemicals' },
    { symbol: 'CELEBRITY.NS', name: 'Celebrity Fashion', sector: 'Textiles' },
    { symbol: 'CENTUM.NS', name: 'Centum Electronics', sector: 'Electronics' },
    { symbol: 'CENTRUM.NS', name: 'Centrum Capital', sector: 'Finance' },
    { symbol: 'CENTURYPLY.NS', name: 'Century Plyboards', sector: 'Building Materials' },
    { symbol: 'CENTURYTEX.NS', name: 'Century Textiles', sector: 'Textiles' },
    { symbol: 'CERA.NS', name: 'Cera Sanitaryware', sector: 'Consumer' },
    { symbol: 'CHALET.NS', name: 'Chalet Hotels', sector: 'Hotels' },
    { symbol: 'CHAMBLFERT.NS', name: 'Chambal Fertilisers', sector: 'Fertilizers' },
    { symbol: 'CHEMCON.NS', name: 'Chemcon Speciality', sector: 'Chemicals' },
    { symbol: 'CHEMFAB.NS', name: 'Chemfab Alkalis', sector: 'Chemicals' },
    { symbol: 'CHENNPETRO.NS', name: 'Chennai Petroleum', sector: 'Oil & Gas' },
    { symbol: 'CHOLAHLDNG.NS', name: 'Cholamandalam Investment', sector: 'Finance' },
    { symbol: 'CIGNITI.NS', name: 'Cigniti Technologies', sector: 'IT' },
    { symbol: 'CL.NS', name: 'CL Educate', sector: 'Education' },
    { symbol: 'CLSEL.NS', name: 'Chembond Chemicals', sector: 'Chemicals' },
    { symbol: 'CMICABLES.NS', name: 'CMI', sector: 'Cables' },
    { symbol: 'COCHIN.NS', name: 'Cochin Minerals', sector: 'Mining' },
    { symbol: 'COFFEEDAY.NS', name: 'Coffee Day Enterprises', sector: 'QSR' },
    { symbol: 'COMPINFO.NS', name: 'Comp Info Systems', sector: 'IT' },
    { symbol: 'COMPUAGE.NS', name: 'Compuage Infocom', sector: 'IT' },
    { symbol: 'CONFIPET.NS', name: 'Confidence Petroleum', sector: 'Oil & Gas' },
    { symbol: 'CONSOLLID.NS', name: 'Consolidated Securities', sector: 'Finance' },
    { symbol: 'CONTROLPR.NS', name: 'Control Print', sector: 'Industrial' },
    { symbol: 'CORALFINAC.NS', name: 'Coral Finance', sector: 'Finance' },
    { symbol: 'CORDSCABLE.NS', name: 'Cords Cable', sector: 'Cables' },
    { symbol: 'COROMANDEL.NS', name: 'Coromandel International', sector: 'Agrochemicals' },
    { symbol: 'COSMOFILMS.NS', name: 'Cosmo Films', sector: 'Packaging' },
    { symbol: 'CPSYSTEMS.NS', name: 'C P Systems', sector: 'IT' },
    { symbol: 'CREATIVE.NS', name: 'Creative Peripherals', sector: 'IT' },
    { symbol: 'CREATIVEYE.NS', name: 'Creative Eye', sector: 'Media' },
    { symbol: 'CREDITACC.NS', name: 'CreditAccess Grameen', sector: 'Finance' },
    { symbol: 'CREST.NS', name: 'Crest Ventures', sector: 'Finance' },
    { symbol: 'CRISIL.NS', name: 'CRISIL', sector: 'Finance' },
    { symbol: 'CROMPTON.NS', name: 'Crompton Greaves', sector: 'Consumer' },
    { symbol: 'CROWN.NS', name: 'Crown Lifters', sector: 'Capital Goods' },
    { symbol: 'CSBBANK.NS', name: 'CSB Bank', sector: 'Banking' },
    { symbol: 'CTE.NS', name: 'Cambridge Technology', sector: 'IT' },
    { symbol: 'CUB.NS', name: 'City Union Bank', sector: 'Banking' },
    { symbol: 'CUPID.NS', name: 'Cupid', sector: 'Healthcare' },
    { symbol: 'CYBERTECH.NS', name: 'CyberTech Systems', sector: 'IT' },
    
    // SME Stocks (D-E)
    { symbol: 'DAAWAT.NS', name: 'KRBL Foods', sector: 'Rice' },
    { symbol: 'DABUR.NS', name: 'Dabur India', sector: 'FMCG' },
    { symbol: 'DALMIASUG.NS', name: 'Dalmia Sugar', sector: 'Sugar' },
    { symbol: 'DANLAW.NS', name: 'Danlaw Technologies', sector: 'IT' },
    { symbol: 'DATAMATIC.NS', name: 'Datamatics', sector: 'IT' },
    { symbol: 'DBREALTY.NS', name: 'D B Realty', sector: 'Real Estate' },
    { symbol: 'DBSTOCKBRO.NS', name: 'DB Stock Broking', sector: 'Finance' },
    { symbol: 'DCAL.NS', name: 'Deccan Cements', sector: 'Cement' },
    { symbol: 'DCBBANK.NS', name: 'DCB Bank', sector: 'Banking' },
    { symbol: 'DCM.NS', name: 'DCM', sector: 'Diversified' },
    { symbol: 'DCMFINSERV.NS', name: 'DCM Financial Services', sector: 'Finance' },
    { symbol: 'DCMNVL.NS', name: 'DCM Nouvelle', sector: 'Textiles' },
    { symbol: 'DCMSHRIRAM.NS', name: 'DCM Shriram', sector: 'Diversified' },
    { symbol: 'DEEPAKFERT.NS', name: 'Deepak Fertilisers', sector: 'Fertilizers' },
    { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite', sector: 'Chemicals' },
    { symbol: 'DEEPIND.NS', name: 'Deep Industries', sector: 'Oil & Gas' },
    { symbol: 'DELTACORP.NS', name: 'Delta Corp', sector: 'Gaming' },
    { symbol: 'DELTAMAGNT.NS', name: 'Delta Manufacturing', sector: 'Manufacturing' },
    { symbol: 'DEN.NS', name: 'Den Networks', sector: 'Media' },
    { symbol: 'DENORA.NS', name: 'De Nora India', sector: 'Capital Goods' },
    { symbol: 'DEVIT.NS', name: 'Dev IT', sector: 'IT' },
    { symbol: 'DHANUKA.NS', name: 'Dhanuka Agritech', sector: 'Agrochemicals' },
    { symbol: 'DHAMPURSUG.NS', name: 'Dhampur Sugar', sector: 'Sugar' },
    { symbol: 'DHARSUGAR.NS', name: 'Dharani Sugars', sector: 'Sugar' },
    { symbol: 'DIAMINES.NS', name: 'Diamines & Chemicals', sector: 'Chemicals' },
    { symbol: 'DIAMONDYD.NS', name: 'Diamond Power', sector: 'Cables' },
    { symbol: 'DIOL.NS', name: 'DI Security', sector: 'Finance' },
    { symbol: 'DISCRETE.NS', name: 'Discrete Software', sector: 'IT' },
    { symbol: 'DJIND.NS', name: 'DJ Industries', sector: 'Engineering' },
    { symbol: 'DLINKINDIA.NS', name: 'D-Link India', sector: 'IT' },
    { symbol: 'DOLPHIN.NS', name: 'Dolphin Offshore', sector: 'Oil & Gas' },
    { symbol: 'DOMIND.NS', name: 'Domestic Appliances', sector: 'Consumer' },
    { symbol: 'DRSDILIP.NS', name: 'DRS Dilip Roadlines', sector: 'Logistics' },
    { symbol: 'DSSL.NS', name: 'Dynacons Systems', sector: 'IT' },
    { symbol: 'DTIL.NS', name: 'Dhanashree Industries', sector: 'Manufacturing' },
    { symbol: 'DVL.NS', name: 'Dhunseri Ventures', sector: 'Diversified' },
    { symbol: 'DYNAMATECH.NS', name: 'Dynamatic Technologies', sector: 'Capital Goods' },
    { symbol: 'DYNPRO.NS', name: 'Dynamic Products', sector: 'Manufacturing' },
    
    // SME Stocks (E-F-G)
    { symbol: 'EASTSILK.NS', name: 'Eastern Silk', sector: 'Textiles' },
    { symbol: 'EASUNREYRO.NS', name: 'Easun Reyrolle', sector: 'Capital Goods' },
    { symbol: 'ECLERX.NS', name: 'eClerx Services', sector: 'IT' },
    { symbol: 'EDELWEISS.NS', name: 'Edelweiss Financial', sector: 'Finance' },
    { symbol: 'EDUCOMP.NS', name: 'Educomp Solutions', sector: 'Education' },
    { symbol: 'EICHER.NS', name: 'Eicher Motors', sector: 'Auto' },
    { symbol: 'EKC.NS', name: 'Everest Kanto', sector: 'Manufacturing' },
    { symbol: 'ELCITECH.NS', name: 'Elgi Equipments', sector: 'Capital Goods' },
    { symbol: 'ELDEHSG.NS', name: 'Eldeco Housing', sector: 'Real Estate' },
    { symbol: 'ELECON.NS', name: 'Elecon Engineering', sector: 'Capital Goods' },
    { symbol: 'ELECTCAST.NS', name: 'Electrosteel Castings', sector: 'Metals' },
    { symbol: 'ELECTHERM.NS', name: 'Electrotherm', sector: 'Metals' },
    { symbol: 'ELGIRUBCO.NS', name: 'Elgi Rubber', sector: 'Rubber' },
    { symbol: 'ELIN.NS', name: 'Elin Electronics', sector: 'Electronics' },
    { symbol: 'EMAMILTD.NS', name: 'Emami', sector: 'FMCG' },
    { symbol: 'EMAMIREAL.NS', name: 'Emami Realty', sector: 'Real Estate' },
    { symbol: 'EMCO.NS', name: 'Emco', sector: 'Capital Goods' },
    { symbol: 'EMKAY.NS', name: 'Emkay Global', sector: 'Finance' },
    { symbol: 'EMMBI.NS', name: 'Emmbi Industries', sector: 'Packaging' },
    { symbol: 'EMPSYSG.NS', name: 'Empyrean Systems', sector: 'IT' },
    { symbol: 'ENCORIND.NS', name: 'Encore India', sector: 'IT' },
    { symbol: 'ENERGYDEV.NS', name: 'Energy Development', sector: 'Power' },
    { symbol: 'ENGINERSIN.NS', name: 'Engineers India', sector: 'Engineering' },
    { symbol: 'ENIL.NS', name: 'Entertainment Network', sector: 'Media' },
    { symbol: 'EOTL.NS', name: 'EOT Cranes', sector: 'Capital Goods' },
    { symbol: 'EPL.NS', name: 'EPL', sector: 'Packaging' },
    { symbol: 'EQUIPPP.NS', name: 'Equipments India', sector: 'Capital Goods' },
    { symbol: 'ERIS.NS', name: 'Eris Lifesciences', sector: 'Pharma' },
    { symbol: 'EROSMEDIA.NS', name: 'Eros International', sector: 'Media' },
    { symbol: 'ESABINDIA.NS', name: 'ESAB India', sector: 'Capital Goods' },
    { symbol: 'ESCORTS.NS', name: 'Escorts Kubota', sector: 'Auto' },
    { symbol: 'ESSARSHIP.NS', name: 'Essar Shipping', sector: 'Shipping' },
    { symbol: 'ESTER.NS', name: 'Ester Industries', sector: 'Packaging' },
    { symbol: 'ETERNAL.NS', name: 'Eternal Saree', sector: 'Textiles' },
    { symbol: 'EUROTEXIND.NS', name: 'Eurotex Industries', sector: 'Textiles' },
    { symbol: 'EVEREADY.NS', name: 'Eveready Industries', sector: 'Consumer' },
    { symbol: 'EVERESTIND.NS', name: 'Everest Industries', sector: 'Building Materials' },
    { symbol: 'EXCEL.NS', name: 'Excel Industries', sector: 'Chemicals' },
    { symbol: 'EXCELCROP.NS', name: 'Excel Crop Care', sector: 'Agrochemicals' },
    { symbol: 'EXIDEIND.NS', name: 'Exide Industries', sector: 'Auto Parts' },
    { symbol: 'EXXARO.NS', name: 'Exxaro Tiles', sector: 'Building Materials' },
    
    // SME Stocks (F)
    { symbol: 'FAIRCHEM.NS', name: 'Fairchem Organics', sector: 'Chemicals' },
    { symbol: 'FAZE3Q.NS', name: 'Faze Three', sector: 'Textiles' },
    { symbol: 'FCL.NS', name: 'Fineotex Chemical', sector: 'Chemicals' },
    { symbol: 'FCONSUMER.NS', name: 'Future Consumer', sector: 'Retail' },
    { symbol: 'FCSSOFT.NS', name: 'FCS Software', sector: 'IT' },
    { symbol: 'FDC.NS', name: 'FDC', sector: 'Pharma' },
    { symbol: 'FEDERALBNK.NS', name: 'Federal Bank', sector: 'Banking' },
    { symbol: 'FEL.NS', name: 'Future Enterprises', sector: 'Retail' },
    { symbol: 'FELDVR.NS', name: 'Fedder Lloyd', sector: 'Capital Goods' },
    { symbol: 'FIBERWEB.NS', name: 'Fiberweb India', sector: 'Textiles' },
    { symbol: 'FIEMIND.NS', name: 'Fiem Industries', sector: 'Auto Parts' },
    { symbol: 'FILATEX.NS', name: 'Filatex India', sector: 'Textiles' },
    { symbol: 'FILMCITY.NS', name: 'Film City Media', sector: 'Media' },
    { symbol: 'FINOPB.NS', name: 'Fino Payments Bank', sector: 'Banking' },
    { symbol: 'FINPIPE.NS', name: 'Finolex Pipes', sector: 'Pipes' },
    { symbol: 'FIRSTWIN.NS', name: 'First Winner', sector: 'SME' },
    { symbol: 'FIVESTAR.NS', name: 'Five Star Business', sector: 'Finance' },
    { symbol: 'FLEXITUFF.NS', name: 'Flexituff Ventures', sector: 'Packaging' },
    { symbol: 'FLY.NS', name: 'Fly Organics', sector: 'Chemicals' },
    { symbol: 'FOKUS.NS', name: 'Fokus Telco', sector: 'Telecom' },
    { symbol: 'FOODSIN.NS', name: 'Foods & Inns', sector: 'Food' },
    { symbol: 'FORCEFIN.NS', name: 'Force Finance', sector: 'Finance' },
    { symbol: 'FORCEMOT.NS', name: 'Force Motors', sector: 'Auto' },
    { symbol: 'FORTUNEINF.NS', name: 'Fortune Infra', sector: 'Infrastructure' },
    { symbol: 'FOSECOIND.NS', name: 'Foseco India', sector: 'Chemicals' },
    { symbol: 'FRETAIL.NS', name: 'Future Retail', sector: 'Retail' },
    { symbol: 'FSC.NS', name: 'Fertilisers & Chemicals', sector: 'Fertilizers' },
    { symbol: 'FSTOCK.NS', name: 'Focus Stocks', sector: 'Finance' },
    { symbol: 'FUTURELIFE.NS', name: 'Future Lifestyle', sector: 'Retail' },
    
    // SME Stocks (G)
    { symbol: 'GABRIEL.NS', name: 'Gabriel India', sector: 'Auto Parts' },
    { symbol: 'GALFLOAT.NS', name: 'Gallant Float', sector: 'Manufacturing' },
    { symbol: 'GALAXYSURL.NS', name: 'Galaxy Surfactants', sector: 'Chemicals' },
    { symbol: 'GALLANTT.NS', name: 'Gallantt Ispat', sector: 'Metals' },
    { symbol: 'GANDHITUBE.NS', name: 'Gandhi Special Tubes', sector: 'Engineering' },
    { symbol: 'GANECOS.NS', name: 'Ganesha Ecosphere', sector: 'Textiles' },
    { symbol: 'GANESHBE.NS', name: 'Ganesh Benzoplast', sector: 'Chemicals' },
    { symbol: 'GANESHHOUC.NS', name: 'Ganesh Housing', sector: 'Real Estate' },
    { symbol: 'GANGES.NS', name: 'Ganges Securities', sector: 'Finance' },
    { symbol: 'GARFIBRES.NS', name: 'Garware Technical Fibres', sector: 'Textiles' },
    { symbol: 'GARWARE.NS', name: 'Garware Hi-Tech', sector: 'Plastics' },
    { symbol: 'GATEWAY.NS', name: 'Gateway Distriparks', sector: 'Logistics' },
    { symbol: 'GAYAPROJ.NS', name: 'Gaya Projects', sector: 'Infrastructure' },
    { symbol: 'GCC.NS', name: 'Gujarat Carbon', sector: 'Chemicals' },
    { symbol: 'GDL.NS', name: 'Gateway Distriparks', sector: 'Logistics' },
    { symbol: 'GEECEE.NS', name: 'GeeCee Ventures', sector: 'Diversified' },
    { symbol: 'GEEIND.NS', name: 'Gee Industries', sector: 'Capital Goods' },
    { symbol: 'GENESYS.NS', name: 'Genesys Intl', sector: 'IT' },
    { symbol: 'GENUSPOWER.NS', name: 'Genus Power', sector: 'Capital Goods' },
    { symbol: 'GEOJITFSL.NS', name: 'Geojit Financial', sector: 'Finance' },
    { symbol: 'GEPIL.NS', name: 'GE Power India', sector: 'Capital Goods' },
    { symbol: 'GFLLIMITED.NS', name: 'GFL', sector: 'Chemicals' },
    { symbol: 'GHCL.NS', name: 'GHCL', sector: 'Chemicals' },
    { symbol: 'GICHSGFIN.NS', name: 'GIC Housing Finance', sector: 'Finance' },
    { symbol: 'GILLANDERS.NS', name: 'Gillanders Arbuthnot', sector: 'Diversified' },
    { symbol: 'GINNIFILA.NS', name: 'Ginni Filaments', sector: 'Textiles' },
    { symbol: 'GITARENEW.NS', name: 'Gita Renewable', sector: 'Power' },
    { symbol: 'GKWLIMITED.NS', name: 'GKW', sector: 'Capital Goods' },
    { symbol: 'GLAXO.NS', name: 'GlaxoSmithKline Pharma', sector: 'Pharma' },
    { symbol: 'GLENMARK.NS', name: 'Glenmark Pharma', sector: 'Pharma' },
    { symbol: 'GLFL.NS', name: 'GL Finance', sector: 'Finance' },
    { symbol: 'GLOBALVECT.NS', name: 'Global Vectra', sector: 'Aviation' },
    { symbol: 'GLOBOFFS.NS', name: 'Global Offshore', sector: 'Oil & Gas' },
    { symbol: 'GLOBUSSPR.NS', name: 'Globus Spirits', sector: 'Beverages' },
    { symbol: 'GLORY.NS', name: 'Glory Polyfilms', sector: 'Packaging' },
    { symbol: 'GLS.NS', name: 'GLS Research', sector: 'IT' },
    { symbol: 'GLUMANURG.NS', name: 'GM Polyplast', sector: 'Plastics' },
    { symbol: 'GMDC.NS', name: 'Gujarat Mineral', sector: 'Mining' },
    { symbol: 'GMDCLTD.NS', name: 'GMDC', sector: 'Mining' },
    { symbol: 'GMBREW.NS', name: 'GM Breweries', sector: 'Beverages' },
    { symbol: 'GMMPFAUDLR.NS', name: 'GMM Pfaudler', sector: 'Capital Goods' },
    { symbol: 'GMRINFRA.NS', name: 'GMR Airports Infra', sector: 'Infrastructure' },
    { symbol: 'GNA.NS', name: 'GNA Axles', sector: 'Auto Parts' },
    { symbol: 'GNFC.NS', name: 'Gujarat Narmada', sector: 'Chemicals' },
    { symbol: 'GOACARBON.NS', name: 'Goa Carbon', sector: 'Chemicals' },
    { symbol: 'GOCLCORP.NS', name: 'GOCL Corporation', sector: 'Chemicals' },
    { symbol: 'GODAWARI.NS', name: 'Godawari Power', sector: 'Metals' },
    { symbol: 'GODFRYPHLP.NS', name: 'Godfrey Phillips', sector: 'Tobacco' },
    { symbol: 'GOENKA.NS', name: 'Goenka Diamond', sector: 'Gems' },
    { symbol: 'GOKEX.NS', name: 'Gokaldas Exports', sector: 'Textiles' },
    { symbol: 'GOKUL.NS', name: 'Gokul Refoils', sector: 'Edible Oil' },
    { symbol: 'GOKULAGRO.NS', name: 'Gokul Agro Resources', sector: 'Agro' },
    { symbol: 'GOLDENTOBC.NS', name: 'Golden Tobacco', sector: 'Tobacco' },
    { symbol: 'GOLDIAM.NS', name: 'Goldiam International', sector: 'Gems' },
    { symbol: 'GOLDTECH.NS', name: 'Goldstone Technologies', sector: 'IT' },
    { symbol: 'GOODLUCK.NS', name: 'Goodluck India', sector: 'Metals' },
    { symbol: 'GOODYEAR.NS', name: 'Goodyear India', sector: 'Tyres' },
    { symbol: 'GPIL.NS', name: 'Godawari Power', sector: 'Metals' },
    { symbol: 'GPRIND.NS', name: 'GPR Industries', sector: 'Manufacturing' },
    { symbol: 'GPL.NS', name: 'Geojit BNP', sector: 'Finance' },
    { symbol: 'GPPL.NS', name: 'Gujarat Pipavav Port', sector: 'Ports' },
    { symbol: 'GRANULES.NS', name: 'Granules India', sector: 'Pharma' },
    { symbol: 'GRAPHITE.NS', name: 'Graphite India', sector: 'Capital Goods' },
    { symbol: 'GRASIM.NS', name: 'Grasim Industries', sector: 'Cement' },
    { symbol: 'GRAVITA.NS', name: 'Gravita India', sector: 'Metals' },
    { symbol: 'GRBFIN.NS', name: 'GRB Finance', sector: 'Finance' },
    { symbol: 'GREAVESCOT.NS', name: 'Greaves Cotton', sector: 'Capital Goods' },
    { symbol: 'GREENPANEL.NS', name: 'Greenpanel Industries', sector: 'Building Materials' },
    { symbol: 'GREENPLY.NS', name: 'Greenply Industries', sector: 'Building Materials' },
    { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton', sector: 'Capital Goods' },
    { symbol: 'GRMOVER.NS', name: 'GRM Overseas', sector: 'Rice' },
    { symbol: 'GROBTEA.NS', name: 'Grob Tea', sector: 'Tea' },
    { symbol: 'GRPLTD.NS', name: 'GRP', sector: 'Rubber' },
    { symbol: 'GRSE.NS', name: 'Garden Reach Shipbuilders', sector: 'Defence' },
    { symbol: 'GSAUTO.NS', name: 'GS Auto International', sector: 'Auto Parts' },
    { symbol: 'GSS.NS', name: 'GSS Infotech', sector: 'IT' },
    
    // ============================================
    // BSE EXCLUSIVE STOCKS (Not on NSE)
    // ============================================
    { symbol: 'ABHIINFRA.BO', name: 'Abhi Infrastructure', sector: 'Infrastructure' },
    { symbol: 'ACCURACAP.BO', name: 'Accurate Capital', sector: 'Finance' },
    { symbol: 'ADFFOODS.BO', name: 'ADF Foods', sector: 'Food' },
    { symbol: 'ADHUNIK.BO', name: 'Adhunik Industries', sector: 'Metals' },
    { symbol: 'ADVENZYMES.BO', name: 'Advanced Enzymes', sector: 'Biotech' },
    { symbol: 'AGARIND.BO', name: 'Agarwal Industrial', sector: 'Capital Goods' },
    { symbol: 'AGRITECH.BO', name: 'Agri-Tech India', sector: 'Agro' },
    { symbol: 'AHMEDFORGE.BO', name: 'Ahmedabad Forge', sector: 'Engineering' },
    { symbol: 'AIAENG.BO', name: 'AIA Engineering', sector: 'Capital Goods' },
    { symbol: 'AIRAN.BO', name: 'Airan', sector: 'Diversified' },
    { symbol: 'AJCON.BO', name: 'Ajcon Global Services', sector: 'Finance' },
    { symbol: 'AKASHDEEP.BO', name: 'Akash Deep', sector: 'IT' },
    { symbol: 'AKSHAY.BO', name: 'Akshay Software', sector: 'IT' },
    { symbol: 'ALEMBICLTD.BO', name: 'Alembic', sector: 'Pharma' },
    { symbol: 'ALFRED.BO', name: 'Alfred Herbert', sector: 'Capital Goods' },
    { symbol: 'ALLIANCE.BO', name: 'Alliance Integrated', sector: 'Metals' },
    { symbol: 'ALLSEC.BO', name: 'Allsec Technologies', sector: 'IT' },
    { symbol: 'ALPHA.BO', name: 'Alpha Hi-Tech Fuel', sector: 'Oil & Gas' },
    { symbol: 'ALPHAGEO.BO', name: 'Alphageo India', sector: 'Oil & Gas' },
    { symbol: 'AMAZING.BO', name: 'Amazing Hydrocarbon', sector: 'Oil & Gas' },
    { symbol: 'AMBCAPS.BO', name: 'Amban Capital', sector: 'Finance' },
    { symbol: 'AMJLAND.BO', name: 'AMJ Land Holdings', sector: 'Real Estate' },
    { symbol: 'AMMPL.BO', name: 'AMML', sector: 'Manufacturing' },
    { symbol: 'AMRAPALI.BO', name: 'Amrapali Industries', sector: 'Food' },
    { symbol: 'ANDCITY.BO', name: 'Andhra City Finance', sector: 'Finance' },
    { symbol: 'ANDHPAPER.BO', name: 'Andhra Paper', sector: 'Paper' },
    { symbol: 'ANDHSUGIR.BO', name: 'Andhra Sugars', sector: 'Sugar' },
    { symbol: 'ANGELONE.BO', name: 'Angel One', sector: 'Finance' },
    { symbol: 'ANNAAMAL.BO', name: 'Anna Investment', sector: 'Finance' },
    { symbol: 'ANTGRAPHIC.BO', name: 'ANT Graphics', sector: 'Packaging' },
    { symbol: 'ANUP.BO', name: 'Anup Engineering', sector: 'Capital Goods' },
    { symbol: 'APARIND.BO', name: 'Apar Industries', sector: 'Cables' },
    { symbol: 'APEX.BO', name: 'Apex Frozen Foods', sector: 'Food' },
    { symbol: 'APLLTD.BO', name: 'Alembic Pharma', sector: 'Pharma' },
    { symbol: 'APOLLOPIPE.BO', name: 'Apollo Pipes', sector: 'Pipes' },
    { symbol: 'APOLLOTYRES.BO', name: 'Apollo Tyres', sector: 'Tyres' },
    { symbol: 'APTPACK.BO', name: 'APT Packaging', sector: 'Packaging' },
    { symbol: 'AQUA.BO', name: 'Aqua Infrastructure', sector: 'Infrastructure' },
    { symbol: 'ARCHANA.BO', name: 'Archana Software', sector: 'IT' },
    { symbol: 'ARCHIDJUTE.BO', name: 'Archidply Decor', sector: 'Building Materials' },
    { symbol: 'ARDLABS.BO', name: 'ARD Laboratories', sector: 'Pharma' },
    { symbol: 'ARFIN.BO', name: 'Arfin India', sector: 'Finance' },
    { symbol: 'ARIHANTCAP.BO', name: 'Arihant Capital', sector: 'Finance' },
    { symbol: 'ARL.BO', name: 'Arihant Rajlaxmi', sector: 'Textiles' },
    { symbol: 'ARMAANFIN.BO', name: 'Armaan Finance', sector: 'Finance' },
    { symbol: 'AROAROMA.BO', name: 'ARO Aroma', sector: 'Chemicals' },
    { symbol: 'ARSHIYA.BO', name: 'Arshiya', sector: 'Logistics' },
    { symbol: 'ARTEMISMED.BO', name: 'Artemis Medicare', sector: 'Healthcare' },
    { symbol: 'ARTNIRMAN.BO', name: 'Art Nirman', sector: 'Infrastructure' },
    { symbol: 'ASAHIINDA.BO', name: 'Asahi India Glass', sector: 'Glass' },
    { symbol: 'ASHAPURA.BO', name: 'Ashapura Minechem', sector: 'Mining' },
    { symbol: 'ASHIRVAD.BO', name: 'Ashirvad Capital', sector: 'Finance' },
    { symbol: 'ASHTVINIT.BO', name: 'Ashtvinit Enterprises', sector: 'Diversified' },
    { symbol: 'ASIAN.BO', name: 'Asian Capital', sector: 'Finance' },
    { symbol: 'ASIANTILES.BO', name: 'Asian Tiles', sector: 'Building Materials' },
    { symbol: 'ASPINWALL.BO', name: 'Aspinwall & Co', sector: 'Logistics' },
    { symbol: 'ASSOCIATED.BO', name: 'Associated Alcohols', sector: 'Beverages' },
    { symbol: 'ASTRAL.BO', name: 'Astral Pipes', sector: 'Pipes' },
    { symbol: 'ASTRONOMIC.BO', name: 'Astronomic Finance', sector: 'Finance' },
    { symbol: 'ATHARVENT.BO', name: 'Atharv Enterprises', sector: 'Diversified' },
    { symbol: 'ATLANTIC.BO', name: 'Atlantic Industries', sector: 'Textiles' },
    { symbol: 'ATLASBIA.BO', name: 'Atlas Cycles', sector: 'Consumer' },
    { symbol: 'AUTOLITE.BO', name: 'Autolite India', sector: 'Auto Parts' },
    { symbol: 'AUTOPAL.BO', name: 'Autopal Industries', sector: 'Auto Parts' },
    { symbol: 'AVANCE.BO', name: 'Avance Technologies', sector: 'IT' },
    { symbol: 'AVENTIS.BO', name: 'Sanofi India', sector: 'Pharma' },
    { symbol: 'AVG.BO', name: 'AVG Logistics', sector: 'Logistics' },
    { symbol: 'AVOSEC.BO', name: 'AVO Securities', sector: 'Finance' },
    
    // More BSE Stocks (B-C-D-E-F)
    { symbol: 'BAGFILMS.BO', name: 'BAG Films & Media', sector: 'Media' },
    { symbol: 'BAJAJEL.BO', name: 'Bajaj Electricals', sector: 'Consumer' },
    { symbol: 'BALKRISIND.BO', name: 'Balkrishna Industries', sector: 'Tyres' },
    { symbol: 'BANARBEADS.BO', name: 'Banas Beads', sector: 'Gems' },
    { symbol: 'BANCOINDIA.BO', name: 'Banco Products', sector: 'Auto Parts' },
    { symbol: 'BANGALOREF.BO', name: 'Bangalore Fort', sector: 'Infrastructure' },
    { symbol: 'BANSAL.BO', name: 'Bansal Wire Industries', sector: 'Metals' },
    { symbol: 'BAREJA.BO', name: 'Bareja Agro', sector: 'Agro' },
    { symbol: 'BASANT.BO', name: 'Basant Agro', sector: 'Agro' },
    { symbol: 'BASFINDIA.BO', name: 'BASF India', sector: 'Chemicals' },
    { symbol: 'BATLIBOI.BO', name: 'Batilboi', sector: 'Capital Goods' },
    { symbol: 'BAYERCROP.BO', name: 'Bayer CropScience', sector: 'Agrochemicals' },
    { symbol: 'BEACONIND.BO', name: 'Beacon Industries', sector: 'Textiles' },
    { symbol: 'BECTOR.BO', name: 'Bector Foods', sector: 'FMCG' },
    { symbol: 'BEEYU.BO', name: 'Beeyu Overseas', sector: 'Textiles' },
    { symbol: 'BELLSEC.BO', name: 'Bell Securities', sector: 'Finance' },
    { symbol: 'BEPL.BO', name: 'Bhansali Engineering', sector: 'Chemicals' },
    { symbol: 'BHAGWANT.BO', name: 'Bhagwant Group', sector: 'Diversified' },
    { symbol: 'BHAGYAPROP.BO', name: 'Bhagya Properties', sector: 'Real Estate' },
    { symbol: 'BHARATWIRE.BO', name: 'Bharat Wire Ropes', sector: 'Capital Goods' },
    { symbol: 'BHILSTEEL.BO', name: 'Bhilwara Spinners', sector: 'Textiles' },
    { symbol: 'BIGBLOCK.BO', name: 'Big Block Construction', sector: 'Real Estate' },
    { symbol: 'BLKASHYAP.BO', name: 'B L Kashyap', sector: 'Infrastructure' },
    { symbol: 'BLUEBLEND.BO', name: 'Blue Blends', sector: 'Diversified' },
    { symbol: 'BLUECHIP.BO', name: 'Blue Chip India', sector: 'Finance' },
    { symbol: 'BLUECHEM.BO', name: 'Blue Chemicals', sector: 'Chemicals' },
    { symbol: 'BLUECOAST.BO', name: 'Blue Coast Hotels', sector: 'Hotels' },
    { symbol: 'BMCSTEEL.BO', name: 'BMC Steel', sector: 'Metals' },
    { symbol: 'BMSLTD.BO', name: 'BMS', sector: 'Manufacturing' },
    { symbol: 'BODALCHEM.BO', name: 'Bodal Chemicals', sector: 'Chemicals' },
    { symbol: 'BOMBAYGAS.BO', name: 'Bombay Gas', sector: 'Oil & Gas' },
    { symbol: 'BOMDYEING.BO', name: 'Bombay Dyeing', sector: 'Textiles' },
    { symbol: 'BONTEX.BO', name: 'Bontex Industries', sector: 'Textiles' },
    { symbol: 'BORROMETAL.BO', name: 'Borro Metal', sector: 'Metals' },
    { symbol: 'BPL.BO', name: 'BPL', sector: 'Consumer' },
    { symbol: 'BRISHEALTH.BO', name: 'Bris Healthcare', sector: 'Healthcare' },
    { symbol: 'BRITINDIA.BO', name: 'Brit India', sector: 'Diversified' },
    { symbol: 'BURNPUR.BO', name: 'Burnpur Cement', sector: 'Cement' },
    { symbol: 'CADD.BO', name: 'CADD Industries', sector: 'IT' },
    { symbol: 'CADSEC.BO', name: 'CAD Securities', sector: 'Finance' },
    { symbol: 'CALPACIFIC.BO', name: 'California Pacific', sector: 'IT' },
    { symbol: 'CAMSON.BO', name: 'Camson Bio Tech', sector: 'Biotech' },
    { symbol: 'CANBK.BO', name: 'Canara Bank', sector: 'Banking' },
    { symbol: 'CANDOUR.BO', name: 'Candour Trading', sector: 'Trading' },
    { symbol: 'CANFIN.BO', name: 'Can Fin Homes', sector: 'Finance' },
    { symbol: 'CAPITAL.BO', name: 'Capital Trade', sector: 'Finance' },
    { symbol: 'CAPRIHANS.BO', name: 'Caprihans India', sector: 'Plastics' },
    { symbol: 'CARYSIL.BO', name: 'Carysil', sector: 'Consumer' },
    { symbol: 'CENTBANK.BO', name: 'Central Bank of India', sector: 'Banking' },
    { symbol: 'CENTRAL.BO', name: 'Central Depository', sector: 'Finance' },
    { symbol: 'CENTURIAN.BO', name: 'Centurian Securities', sector: 'Finance' },
    { symbol: 'CHAKRA.BO', name: 'Chakra Industries', sector: 'IT' },
    { symbol: 'CHALLFIN.BO', name: 'Challenge Finance', sector: 'Finance' },
    { symbol: 'CHAMBAL.BO', name: 'Chambal Fertilizers', sector: 'Fertilizers' },
    { symbol: 'CHAMPIONS.BO', name: 'Champions Industries', sector: 'Diversified' },
    { symbol: 'CHANDGN.BO', name: 'Chandni Textiles', sector: 'Textiles' },
    { symbol: 'CHANDRA.BO', name: 'Chandra Prabhu', sector: 'Finance' },
    { symbol: 'CHEMIESYNT.BO', name: 'Chemiesynth', sector: 'Chemicals' },
    { symbol: 'CHENNPETRO.BO', name: 'Chennai Petroleum', sector: 'Oil & Gas' },
    { symbol: 'CHOICELEASI.BO', name: 'Choice Leasing', sector: 'Finance' },
    { symbol: 'CINNAMON.BO', name: 'Cinnamon Finance', sector: 'Finance' },
    { symbol: 'CITATION.BO', name: 'Citation Finance', sector: 'Finance' },
    { symbol: 'CITTEX.BO', name: 'Citurgia Biochemicals', sector: 'Chemicals' },
    { symbol: 'CITYONLINE.BO', name: 'City Online Services', sector: 'IT' },
    { symbol: 'CLASSIC.BO', name: 'Classic Diamonds', sector: 'Gems' },
    { symbol: 'CLUBSAND.BO', name: 'Club Sands', sector: 'Hotels' },
    { symbol: 'CMIFPE.BO', name: 'CMI FPE', sector: 'Capital Goods' },
    { symbol: 'COASTAL.BO', name: 'Coastal Roadways', sector: 'Logistics' },
    { symbol: 'COMPETENT.BO', name: 'Competent Automobiles', sector: 'Auto Parts' },
    { symbol: 'COMPULEARN.BO', name: 'CompuLearn', sector: 'Education' },
    { symbol: 'COMPUSOFT.BO', name: 'CompuSoft', sector: 'IT' },
    { symbol: 'CONCEPT.BO', name: 'Concept Communications', sector: 'Media' },
    { symbol: 'CONFIPET.BO', name: 'Confidence Petroleum', sector: 'Oil & Gas' },
    { symbol: 'CONINTL.BO', name: 'Continental Controls', sector: 'Electronics' },
    { symbol: 'CONPLAS.BO', name: 'Continental Plastics', sector: 'Plastics' },
    { symbol: 'CONTINETAL.BO', name: 'Continental Securities', sector: 'Finance' },
    { symbol: 'CONTROLPR.BO', name: 'Control Print', sector: 'Industrial' },
    { symbol: 'CORALLAB.BO', name: 'Coral Laboratories', sector: 'Pharma' },
    { symbol: 'CORDSCABLE.BO', name: 'Cords Cable', sector: 'Cables' },
    { symbol: 'CORONATION.BO', name: 'Coronation Agro', sector: 'Agro' },
    { symbol: 'COSMOGREEN.BO', name: 'Cosmo Green', sector: 'Chemicals' },
    { symbol: 'COUNTRYCLB.BO', name: 'Country Club', sector: 'Hotels' },
    { symbol: 'CREATIVE.BO', name: 'Creative Castings', sector: 'Auto Parts' },
    { symbol: 'CRESCITA.BO', name: 'Crescita Infra', sector: 'Infrastructure' },
    { symbol: 'CREST.BO', name: 'Crest Ventures', sector: 'Finance' },
    { symbol: 'CTULTRA.BO', name: 'CT Ultra', sector: 'IT' },
    { symbol: 'CUBESOFT.BO', name: 'Cube Software', sector: 'IT' },
    { symbol: 'CYBERMATE.BO', name: 'Cybermate Infotech', sector: 'IT' },
    { symbol: 'CYBERMEDIA.BO', name: 'Cybermedia', sector: 'Media' },
    
    // More BSE Stocks (D-E-F-G)
    { symbol: 'DAGGER.BO', name: 'Dagger Forst Tools', sector: 'Tools' },
    { symbol: 'DAICHI.BO', name: 'Daichi Karkaria', sector: 'Chemicals' },
    { symbol: 'DAIRY.BO', name: 'Dairy India', sector: 'FMCG' },
    { symbol: 'DALMIABHA.BO', name: 'Dalmia Bharat', sector: 'Cement' },
    { symbol: 'DANUBE.BO', name: 'Danube Industries', sector: 'Chemicals' },
    { symbol: 'DATASOFT.BO', name: 'Datasoft Application', sector: 'IT' },
    { symbol: 'DBFSEC.BO', name: 'DBF Securities', sector: 'Finance' },
    { symbol: 'DCMSTEEL.BO', name: 'DCM Steel', sector: 'Metals' },
    { symbol: 'DEEPIND.BO', name: 'Deep Industries', sector: 'Oil & Gas' },
    { symbol: 'DELTA.BO', name: 'Delta Paper Mills', sector: 'Paper' },
    { symbol: 'DELTALIGHT.BO', name: 'Delta Lighting', sector: 'Capital Goods' },
    { symbol: 'DENORA.BO', name: 'De Nora India', sector: 'Capital Goods' },
    { symbol: 'DESERT.BO', name: 'Desert Securities', sector: 'Finance' },
    { symbol: 'DEVISHARMA.BO', name: 'Devi Sharma', sector: 'Textiles' },
    { symbol: 'DEVSUGAR.BO', name: 'Devi Sugar', sector: 'Sugar' },
    { symbol: 'DHARSUGAR.BO', name: 'Dharani Sugars', sector: 'Sugar' },
    { symbol: 'DIAMOND.BO', name: 'Diamond Cables', sector: 'Cables' },
    { symbol: 'DIGITAL.BO', name: 'Digital Electronics', sector: 'Electronics' },
    { symbol: 'DISA.BO', name: 'DISA India', sector: 'Capital Goods' },
    { symbol: 'DITEL.BO', name: 'Digitial Telelinks', sector: 'IT' },
    { symbol: 'DIVINUS.BO', name: 'Divinus Fab', sector: 'Textiles' },
    { symbol: 'DIVYASHAK.BO', name: 'Divyashakti Granite', sector: 'Building Materials' },
    { symbol: 'DOLLEX.BO', name: 'Dollex Industries', sector: 'Capital Goods' },
    { symbol: 'DOLPHINFIN.BO', name: 'Dolphin Finance', sector: 'Finance' },
    { symbol: 'DOMIND.BO', name: 'Domi Industries', sector: 'Manufacturing' },
    { symbol: 'DOT.BO', name: 'Dot.com Infoway', sector: 'IT' },
    { symbol: 'DRSTONE.BO', name: 'DRS Stone', sector: 'Building Materials' },
    { symbol: 'DUCKCAP.BO', name: 'Duck Capital', sector: 'Finance' },
    { symbol: 'DYNAMIC.BO', name: 'Dynamic Industries', sector: 'Chemicals' },
    { symbol: 'DYNAMICPRO.BO', name: 'Dynamic Products', sector: 'Manufacturing' },
    { symbol: 'EAGLE.BO', name: 'Eagle Finance', sector: 'Finance' },
    { symbol: 'EARTHORGN.BO', name: 'Earth Organics', sector: 'Food' },
    { symbol: 'EASTERN.BO', name: 'Eastern Treads', sector: 'Rubber' },
    { symbol: 'EASTWEST.BO', name: 'Eastwest Agro', sector: 'Agro' },
    { symbol: 'EBOP.BO', name: 'EBOP Electronic', sector: 'Electronics' },
    { symbol: 'ECOPLAST.BO', name: 'Ecoplast', sector: 'Plastics' },
    { symbol: 'EDGFACTOR.BO', name: 'Edge Factory', sector: 'IT' },
    { symbol: 'EDUINFRA.BO', name: 'Edu Infrastructure', sector: 'Education' },
    { symbol: 'EFACTOR.BO', name: 'E-Factor', sector: 'IT' },
    { symbol: 'EIHAHOTELS.BO', name: 'EIH Associated Hotels', sector: 'Hotels' },
    { symbol: 'ELDECO.BO', name: 'Eldeco', sector: 'Real Estate' },
    { symbol: 'ELECTCAST.BO', name: 'Electrosteel Castings', sector: 'Metals' },
    { symbol: 'ELEGINST.BO', name: 'Elgin Instruments', sector: 'Capital Goods' },
    { symbol: 'ELIXIR.BO', name: 'Elixir Cap', sector: 'Finance' },
    { symbol: 'ELLANA.BO', name: 'Ellana Finance', sector: 'Finance' },
    { symbol: 'EMDSL.BO', name: 'EMDS', sector: 'IT' },
    { symbol: 'EMERALD.BO', name: 'Emerald Finance', sector: 'Finance' },
    { symbol: 'EMMBI.BO', name: 'Emmbi Industries', sector: 'Packaging' },
    { symbol: 'EMPIRE.BO', name: 'Empire Industries', sector: 'Diversified' },
    { symbol: 'ENALTEC.BO', name: 'Enaltec Labs', sector: 'Pharma' },
    { symbol: 'ENCASH.BO', name: 'Encash Entertainment', sector: 'Media' },
    { symbol: 'ENERGO.BO', name: 'Energo India', sector: 'Power' },
    { symbol: 'ENNORE.BO', name: 'Ennore Coke', sector: 'Mining' },
    { symbol: 'ENTEG.BO', name: 'Entegra', sector: 'IT' },
    { symbol: 'EPOINT.BO', name: 'E-Point', sector: 'IT' },
    { symbol: 'EQUIPPP.BO', name: 'Equipment India', sector: 'Capital Goods' },
    { symbol: 'ERIKSON.BO', name: 'Erikson Pharma', sector: 'Pharma' },
    { symbol: 'ESSELL.BO', name: 'Essel', sector: 'Diversified' },
    { symbol: 'ESSENTIAL.BO', name: 'Essential Communication', sector: 'IT' },
    { symbol: 'ETECHIE.BO', name: 'E Techies', sector: 'IT' },
    { symbol: 'EURODENIM.BO', name: 'Euro Denim', sector: 'Textiles' },
    { symbol: 'EUROINFO.BO', name: 'Euro Info', sector: 'IT' },
    { symbol: 'EURONET.BO', name: 'Euronet Worldwide', sector: 'IT' },
    { symbol: 'EVEREADY.BO', name: 'Eveready Industries', sector: 'Consumer' },
    { symbol: 'EVERONN.BO', name: 'Everonn Education', sector: 'Education' },
    { symbol: 'EXAMINER.BO', name: 'Examiner Press', sector: 'Paper' },
    { symbol: 'EXDOMAIN.BO', name: 'Exide Domain', sector: 'IT' },
    { symbol: 'EXHIB.BO', name: 'Exhibition', sector: 'Media' },
    { symbol: 'EXPLICITF.BO', name: 'Explicit Finance', sector: 'Finance' },
    { symbol: 'EXPORT.BO', name: 'Export Trading', sector: 'Trading' },
    { symbol: 'EXPRESSFI.BO', name: 'Express Finance', sector: 'Finance' },
    { symbol: 'EXTC.BO', name: 'EXTC Industries', sector: 'Manufacturing' },
    
    // Additional BSE stocks (F-G-H-I-J-K)
    { symbol: 'FACORALL.BO', name: 'Facor Alloys', sector: 'Metals' },
    { symbol: 'FAIRFIELD.BO', name: 'Fairfield Atlas', sector: 'Auto Parts' },
    { symbol: 'FALCON.BO', name: 'Falcon Holdings', sector: 'Finance' },
    { symbol: 'FAME.BO', name: 'Fame India', sector: 'Media' },
    { symbol: 'FAMILYCR.BO', name: 'Family Credit', sector: 'Finance' },
    { symbol: 'FASHION.BO', name: 'Fashion Suiting', sector: 'Textiles' },
    { symbol: 'FASTFIN.BO', name: 'Fast Finance', sector: 'Finance' },
    { symbol: 'FATEHFIN.BO', name: 'Fatehgarh Finance', sector: 'Finance' },
    { symbol: 'FEMTO.BO', name: 'Femto Technologies', sector: 'IT' },
    { symbol: 'FENOPLAST.BO', name: 'Fenoplast', sector: 'Plastics' },
    { symbol: 'FERTCHEM.BO', name: 'Fertilizers & Chem', sector: 'Chemicals' },
    { symbol: 'FIBERWEB.BO', name: 'Fiberweb', sector: 'Textiles' },
    { symbol: 'FICONT.BO', name: 'FI Containers', sector: 'Packaging' },
    { symbol: 'FIEMIND.BO', name: 'Fiem Industries', sector: 'Auto Parts' },
    { symbol: 'FIGFL.BO', name: 'FIG Finance', sector: 'Finance' },
    { symbol: 'FINKURVE.BO', name: 'Finkurve Finance', sector: 'Finance' },
    { symbol: 'FINQUEST.BO', name: 'Finquest Financial', sector: 'Finance' },
    { symbol: 'FIRSTFIN.BO', name: 'First Finance', sector: 'Finance' },
    { symbol: 'FLEXINVEST.BO', name: 'Flex Investment', sector: 'Finance' },
    { symbol: 'FLORENC.BO', name: 'Florence Investech', sector: 'Finance' },
    { symbol: 'FLUIDCONT.BO', name: 'Fluid Control', sector: 'Engineering' },
    { symbol: 'FOCUS.BO', name: 'Focus Industrial', sector: 'Capital Goods' },
    { symbol: 'FONESTAR.BO', name: 'Fonestar', sector: 'Telecom' },
    { symbol: 'FORTUNEPT.BO', name: 'Fortune PT India', sector: 'Diversified' },
    { symbol: 'FRAGRNT.BO', name: 'Fragrant Finance', sector: 'Finance' },
    { symbol: 'FREESOUL.BO', name: 'Free Soul', sector: 'IT' },
    { symbol: 'FRONTIND.BO', name: 'Frontline India', sector: 'Trading' },
    { symbol: 'FRONTLINE.BO', name: 'Frontline Business', sector: 'Diversified' },
    { symbol: 'FUTMEDIA.BO', name: 'Future Media', sector: 'Media' },
    { symbol: 'FWCHEM.BO', name: 'FW Chemicals', sector: 'Chemicals' },
    { symbol: 'GALAXYCAR.BO', name: 'Galaxy Cards', sector: 'Packaging' },
    { symbol: 'GALAX.BO', name: 'Galaxy Entertainment', sector: 'Media' },
    { symbol: 'GALLANTT.BO', name: 'Gallantt Ispat', sector: 'Metals' },
    { symbol: 'GAMMONSEC.BO', name: 'Gammon Sec', sector: 'Infrastructure' },
    { symbol: 'GANAPATHI.BO', name: 'Ganapathi Paper', sector: 'Paper' },
    { symbol: 'GANDHAR.BO', name: 'Gandhar Oil', sector: 'Oil & Gas' },
    { symbol: 'GARDENSILK.BO', name: 'Garden Silk Mills', sector: 'Textiles' },
    { symbol: 'GATISTOCK.BO', name: 'Gati Stock', sector: 'Finance' },
    { symbol: 'GDYNAMIC.BO', name: 'Global Dynamics', sector: 'IT' },
    { symbol: 'GEARAUTO.BO', name: 'Gear Auto', sector: 'Auto Parts' },
    { symbol: 'GECENSOF.BO', name: 'GE Censof', sector: 'IT' },
    { symbol: 'GEECEE.BO', name: 'GeeCee Ventures', sector: 'Diversified' },
    { symbol: 'GEMCO.BO', name: 'Gemco Industries', sector: 'Manufacturing' },
    { symbol: 'GENCON.BO', name: 'General Constructors', sector: 'Infrastructure' },
    { symbol: 'GENERAL.BO', name: 'General Finance', sector: 'Finance' },
    { symbol: 'GENESIS.BO', name: 'Genesis Ibco', sector: 'Diversified' },
    { symbol: 'GENINSYS.BO', name: 'Genius Interactive', sector: 'IT' },
    { symbol: 'GENOPHY.BO', name: 'Genophy', sector: 'IT' },
    { symbol: 'GESTRA.BO', name: 'Gestra', sector: 'IT' },
    { symbol: 'GFSTEELS.BO', name: 'GF Steels', sector: 'Metals' },
    { symbol: 'GGLOBE.BO', name: 'Global Globe', sector: 'Trading' },
    { symbol: 'GGSEC.BO', name: 'GG Securities', sector: 'Finance' },
    { symbol: 'GHCLTEX.BO', name: 'GHCL Textiles', sector: 'Textiles' },
    { symbol: 'GIANT.BO', name: 'Giant Industrial', sector: 'Capital Goods' },
    { symbol: 'GICFINANCE.BO', name: 'GIC Financial', sector: 'Finance' },
    { symbol: 'GLENMARK.BO', name: 'Glenmark Pharma', sector: 'Pharma' },
    { symbol: 'GLFL.BO', name: 'GL Finance', sector: 'Finance' },
    { symbol: 'GLOBALCAP.BO', name: 'Global Capital', sector: 'Finance' },
    { symbol: 'GLOBCHAIN.BO', name: 'Global Chain', sector: 'IT' },
    { symbol: 'GLOBTRADE.BO', name: 'Global Trade', sector: 'Trading' },
    { symbol: 'GLORY.BO', name: 'Glory Industries', sector: 'Packaging' },
    { symbol: 'GLOSTER.BO', name: 'Gloster', sector: 'Textiles' },
    { symbol: 'GMMSEC.BO', name: 'GMM Security', sector: 'Finance' },
    { symbol: 'GODAVARIF.BO', name: 'Godavari Fertilizers', sector: 'Fertilizers' },
    { symbol: 'GOENKABUS.BO', name: 'Goenka Business', sector: 'Diversified' },
    { symbol: 'GOLDCOIN.BO', name: 'Goldcoin Health', sector: 'Food' },
    { symbol: 'GOLDENKWAD.BO', name: 'Golden Quadrilateral', sector: 'Infrastructure' },
    { symbol: 'GOLDINVEST.BO', name: 'Gold Invest', sector: 'Finance' },
    { symbol: 'GOLDMONK.BO', name: 'Golden Monk', sector: 'Finance' },
    { symbol: 'GOLDSHARE.BO', name: 'Gold Share', sector: 'Finance' },
    { symbol: 'GOLDSTONE.BO', name: 'Goldstone Infratech', sector: 'Infrastructure' },
    { symbol: 'GOOD.BO', name: 'Good Industries', sector: 'Textiles' },
    { symbol: 'GOODREM.BO', name: 'Goodrem Industries', sector: 'Diversified' },
    { symbol: 'GOPALA.BO', name: 'Gopala Polyplast', sector: 'Plastics' },
    { symbol: 'GPTINFRA.BO', name: 'GPT Infra Projects', sector: 'Infrastructure' },
    { symbol: 'GRAFTECH.BO', name: 'Graf Technology', sector: 'IT' },
    { symbol: 'GRAINENGI.BO', name: 'Grain Engineering', sector: 'Capital Goods' },
    { symbol: 'GRANDMA.BO', name: 'Grandma Trading', sector: 'Trading' },
    { symbol: 'GRAPHICR.BO', name: 'Graphic Resources', sector: 'Packaging' },
    { symbol: 'GRASIM.BO', name: 'Grasim Industries', sector: 'Cement' },
    { symbol: 'GRBFIN.BO', name: 'GRB Finance', sector: 'Finance' },
    { symbol: 'GREENCREST.BO', name: 'Greencrest Finance', sector: 'Finance' },
    { symbol: 'GREENENERG.BO', name: 'Green Energy', sector: 'Power' },
    { symbol: 'GREENFIRE.BO', name: 'Greenfire Projects', sector: 'Infrastructure' },
    { symbol: 'GREENINF.BO', name: 'Green Infrastructure', sector: 'Infrastructure' },
    { symbol: 'GREENPLY.BO', name: 'Greenply Industries', sector: 'Building Materials' },
    { symbol: 'GRFIN.BO', name: 'GR Finance', sector: 'Finance' },
    { symbol: 'GROWMORE.BO', name: 'Growmore Resources', sector: 'Diversified' },
    { symbol: 'GRPS.BO', name: 'GRP Securities', sector: 'Finance' },
    { symbol: 'GSAUTO.BO', name: 'GS Auto International', sector: 'Auto Parts' },
    { symbol: 'GSSAMERICA.BO', name: 'GSS America', sector: 'IT' },
    { symbol: 'GTPL.BO', name: 'GTPL Hathway', sector: 'Media' },
    { symbol: 'GUARDFIN.BO', name: 'Guardian Finance', sector: 'Finance' },
    { symbol: 'GUFICBIO.BO', name: 'Gufic Biosciences', sector: 'Pharma' },
    { symbol: 'GUJAPOLLO.BO', name: 'Gujarat Apollo', sector: 'Infrastructure' },
    { symbol: 'GUJGAS.BO', name: 'Gujarat Gas', sector: 'Oil & Gas' },
    { symbol: 'GUJHEAVYCH.BO', name: 'Gujarat Heavy Chemicals', sector: 'Chemicals' },
    { symbol: 'GUJINDUSTRI.BO', name: 'Gujarat Industries', sector: 'Power' },
    { symbol: 'GUJRAFFIA.BO', name: 'Gujarat Raffia', sector: 'Packaging' },
    { symbol: 'GUJSIDHEE.BO', name: 'Gujarat Sidhee', sector: 'Cement' },
    { symbol: 'GUJSIDH.BO', name: 'Gujarat Sidhee Cem', sector: 'Cement' },
    { symbol: 'GULFOILLUB.BO', name: 'Gulf Oil Lubricants', sector: 'Oil & Gas' },
    { symbol: 'GVKPIL.BO', name: 'GVK Power', sector: 'Power' },
    { symbol: 'GWRL.BO', name: 'GWRL', sector: 'Textiles' },
];
